### ISSUE TITLE
Find a way to maintain official Chocolatey config here 

### ISSUE THREAD

**Issue by khos2ow** [terraform-docs/terraform-docs#220]
### Prerequisites

Put an `x` into the box that applies:

- [ ] This issue describes a bug.
- [x] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

As discussed in the thread (https://github.com/segmentio/terraform-docs/pull/218#discussion_r391804514) currently the config for maintaining [Chocolatey](http://chocolatey.org/) is being done by @DrFaust92 in https://github.com/DrFaust92/chocolatey-packages/tree/master/terraform-docs.

This issue is here to track the possibility of migrating the work they had done into here as an official source of the config (e.g. may be in `scripts/choco/`)

#### Actual Behavior

n/a

#### Expected Behavior

n/a

### Replication Case

n/a

### Version

You can get this information via `terraform-docs --version`.

**Comment by khos2ow** [comment]
@DrFaust92 do you want to discuss this and find a way to proceed with this issue?

**Comment by DrFaust92** [comment]
@khos2ow , i guess we can start with moving https://github.com/DrFaust92/chocolatey-packages/tree/master/terraform-docs here but im still thinking how we can upload this with some automation because choco requires an API Key and there can be a single key for a a user and it cannot be scoped to a package or some action.

**Comment by khos2ow** [comment]
How does Chocolatey work? Earlier today I opened https://github.com/DrFaust92/chocolatey-packages/pull/1 but just now I noticed the version v0.9.0 is created in Chocolatey ([here](https://chocolatey.org/packages/Terraform-Docs/0.9.0)) and it seems it's actually under review. Didn't we need to merge the PR in your repo first for the package to be create in Chocolatey site?

If there's no relation between your repo and the package on chocolatey site, can we just move it under, let's say, `segmentio/terraform-docs/scripts/choco`?

**Comment by DrFaust92** [comment]
I pushed it to choco today but didn't push the source changes to GitHub
until it's not approved. It can take some time, a moderator needs to go
over it.

I didn't want it to drift from what's updated here in the meantime.

**Comment by khos2ow** [comment]
So what happens if we move the choco configuration from your repo to here? Will it break the way choco package works? Or the moderator will not approve?
I mean if it's a manual process to push the config to choco, does it matter where the configs are?

**Comment by DrFaust92** [comment]
np, i'll open a PR to move sources to this project and we'll see from there.

**Comment by DrFaust92** [comment]
Hey, can you share the username to add as maintainers to the package so you could have full control to deploy it via CI.

**Comment by khos2ow** [comment]
I'm not sure what's needed on my side yet, but may be we can follow up with https://github.com/DrFaust92/chocolatey-packages/issues/3, and move that code in a standalone repo in https://github.com/terraform-docs/ organization and figure it out from there. What do you think?

**Comment by DrFaust92** [comment]
I'll open a PR with the source files. a Choco use is needed on terraform-docs side, after that ill add that user as a maintainer to the package and new changes can be pushed using the aforementioned user.

**Comment by khos2ow** [comment]
I created separate repo for it: https://github.com/terraform-docs/chocolatey-package and added you to that repo as well. Would you please open a PR there?

**Comment by khos2ow** [comment]
Thank you @DrFaust92 for your help on this. We've successfully migrated the code to https://github.com/terraform-docs/chocolatey-package and the packages are updated in https://chocolatey.org/packages/terraform-docs/.
