### ISSUE TITLE
Variable with a regex as default value fails.

### ISSUE THREAD

**Issue by Wiston999** [terraform-docs/terraform-docs#238]
### Prerequisites

Put an `x` into the box that applies:

- [ x ] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

Having a variable with a regex as default value makes the tool fail.

#### Actual Behavior

Briefly describe what happened.

`variables.tf`
```
variable "test_var" {
  type    = string
  default = "int-regex\\d+"
}
```

```
go run main.go markdown test/
Error: template: inputs:10:118: executing "inputs" at <.GetValue>: error calling GetValue: json: error calling MarshalJSON for type types.String: invalid character 'd' in string escape code
```

Do you have long logs to share? Please go to https://ghostbin.com and insert the link here.

#### Expected Behavior

Program should generate a valid output and do not crash.

### Replication Case

Tell us which steps to take to replicate your problem.

1. `mkdir -p test-module`
2. `printf 'variable "test_var" {\n type = string\n default = "int-regex\\\\d+"\n} ' > test-module/variables.tf`
3. `terraform-docs markdown ./test-module`

### Version

You can get this information via `terraform-docs --version`.

```
terraform-docs version v0.10.0-alpha linux/amd64 BuildDate: 2020-04-06T18:17:18+02:00
```

Actually running as `go run main.go` in master branch (Commit `9122e396db6d0ddf20b8153a0b6823b0c700b530`)

**Comment by khos2ow** [comment]
Thank you @Wiston999 for reporting the issue, I was able to reproduce this but haven't been able to come up with a fix for it yet, I'll update the ticket as soon as I figure something out.

**Comment by Wiston999** [comment]
Ok, thanks for taking into consideration.
Congratulations on your work, the tool is very helpful for big modules with a lot of input variables. Looking forward for the fix :smile:

**Comment by Wiston999** [comment]
Just as a note if anyone hits this issue too, I managed to bypass it by replacing `\\d` by `[0-9]`.

**Comment by darrenk13** [comment]
I am also seeing this with a slightly different example:
```
variable "variable_name" {
  type        = string
  default     = "word\\,word2"
}
```

As far as I can tell, the double backslash is triggering the issue.

Error I am seeing:
```
Error: template: inputs:10:118: executing "inputs" at <.GetValue>: error calling GetValue: json: error calling MarshalJSON for type types.String: invalid character ',' in string escape code
```

This is with terraform-docs 0.9.1 and running it as a pre-commit hook.

**Comment by khos2ow** [comment]
Yes @darrenk13 you are correct, the problem is with double backslashes, which unfortunately I still haven't been able to come up with a correct solution for.
