### ISSUE TITLE
Latest version is missing from Chocolatey

### ISSUE THREAD

**Issue by RustyChain** [terraform-docs/terraform-docs#253]
### Prerequisites

- [ x] This issue describes a bug.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

Chocolatey has only the v0.8.2 , but not latest v0.9.1

**Comment by RustyChain** [comment]
I've downloaded the latest version and updated manually in the chocolatey folder. 
That solved the problem.

**Comment by khos2ow** [comment]
@RustyChain We've moved chocolatey package to its own official repository (https://github.com/terraform-docs/chocolatey-package/pull/1), and there's an automation to automatically publish the package.

The latest version on chocolatey should be `v0.10.1`, do you still see this issue happening?
