### ISSUE TITLE
Add documentation on module you depend on

### ISSUE THREAD

**Issue by zopanix** [terraform-docs/terraform-docs#255]
### Prerequisites

Put an `x` into the box that applies:

- [ ] This issue describes a bug.
- [x] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

The goal is to have the ability to have a "dynamic" dependency tree in the documentation. I think this should be in a seperate section.

*Note: I didn't find an issue with this request, but I'm sorry if one already exists*

### Example

```
module "internal" {
  source = "terraform-aws-modules/vpc/aws"
  ...
}

module "external" {
  source = "terraform-aws-modules/vpc/aws"
   version = x.y.z
 ...
}
```

would add a section as follows:

```
## Dependencies
| Name | Module | Version |
| internal | terraform-aws-modules/vpc/aws | N/A |
| external | terraform-aws-modules/vpc/aws | x.y.z |
```

Now, I think that for a first iteration, just fetching the module name, source and version should be enough. Even if it will not be as eye-candy when fetching module directly from git or local modules, these could be future improvements on which one could iterate. I would make the first iteration bluntly simple.

If no module is called, I would do the following:
```
## Dependencies
N/A
```
Just to make sure the user has the information that no dependent module is called.

### Version

`terraform-docs version v0.9.1 7f761d3 linux/amd64 BuildDate: 2020-04-02T21:58:38+0000`

**Comment by skyzyx** [comment]
For my team, one of the things we've worked hard to do is reduce tight coupling in our modules. As such, no module has a "hard" dependency on any other module. Being loosely-coupled, the user does the gluing-together in their code which _consumes_ the modules — not in the modules themselves.

This makes them easier to test (e.g., Terratest), and easier for them to swap out parts with custom parts as necessary for their applications.

Respectfully, I think that adding support for this feature would encourage a behavior which I believe is detrimental to [SOLID engineering principles](https://en.wikipedia.org/wiki/SOLID).

If we're voting, I give this feature request a 👎.

**Comment by tbugfinder** [comment]
Actually I share the request within this issue.
It's common to reuse modules like "terraform-aws-modules/vpc/aws".
Most often those do not include tests utilizing terratest or inspec. Therefore the module might get wrapped within a testing module. Indeed that's a dependency you'd discourage.

**Comment by khos2ow** [comment]
Both of your arguments are valid and the cause of confusion might be the fact the _module_ term in Terraform refers to both 1) UNIX philosophy like _thing_ that does only one thing and 2) the upstream group of _things_ that provisions broader infrastructure and such.

This suggestions, to me, completely makes sense for the latter, and to prevent former's documentation from getting bloated one can always use `--hide modules` in them (if and when this actually gets implemented)

Although implementing it might be challenging due to limitation of how `terraform-config-inspect` works.

**Comment by nitrocode** [comment]
Many open source terraform modules leverage other modules. For example, the [cloudposse ecs alb service task](https://registry.terraform.io/modules/cloudposse/ecs-alb-service-task/aws/latest?tab=dependencies) is incredibly easy off-the-shelf module that has standard inputs to get a container and task definition deployed on an existing ecs cluster. It uses several standardized modules to do this including a popular naming module called [terraform-null-label](https://registry.terraform.io/modules/cloudposse/ecs-alb-service-task/aws/latest?tab=dependencies). Making dependencies easier to document would allow the user to have this information easily available to make better decisions to use the module.

If you click on either of the above module links, you'll go to the terraform registry, and this already has documentation for module and resource dependencies. This feature request would allow it to be documented in private tf modules as well.

**Comment by khos2ow** [comment]
Folks, we have a PR for this under review (#367). It's still at early stage of review and we haven't fully finalized the spec and output details yet. Please feel free to drop your comments or feedbacks here or on the PR.
