### ISSUE TITLE
Show required in a separate table or sort by required

### ISSUE THREAD

**Issue by nitrocode** [terraform-docs/terraform-docs#281]
**Is your feature request related to a problem? Please describe.**

It's easy to find what variables are required using the required section but it could be easier.

**Describe the solution you'd like**

I'd like the ability

* to create a separate table for required variables vs optional variables
* or sort the variables first by required and then alphabetically in the existing table.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by khos2ow** [comment]
Currently there's no option to have a separate table for required variables, although I, now, think that we can add it behind another optional flag of its own for `markdown table` command.

But alternatively you can use `--soet-by-required` and it does exactly what you described one 2nd option. (i.e. sort variables by Name and show the required ones on top)

**Comment by nitrocode** [comment]
I'd prefer a separate table to make it even clearer. Yes, the option you mention is great for now. 

Thank you very much
