### ISSUE TITLE
All sources of the header requires multi-line comment

### ISSUE THREAD

**Issue by antrov** [terraform-docs/terraform-docs#283]
**Describe the bug**

Docs says:

> The whole file content is being extracted as module header when extracting from .adoc, .md or .txt. But to extract header from .tf file you need to use following javascript, c or java like multi-line comment:

In practice, every source of the header (md, adoc, txt) is not attached as a header when content is no wrapped in multiline comment.

**To Reproduce**

1. Clone terraform-docs repo
2. Run `terraform-docs md . --header-from=doc.md > README.MD` in examples folder
3. README.MD has no header
4. Wrap conent of _doc.md_ in comment
5. Rerun command -> header is on his place

**Expected behavior**

Markdown header should be attached to result docs without multiline comment.

**Version information:**

- terraform-docs version v0.0.0- v0.9.1 darwin/amd64 BuildDate: 2020-04-03T02:30:49+0100
- macOS 10.15.5

**Additional context**

N/A

**Comment by khos2ow** [comment]
I'm not sure if I understand the issue correctly. If you look at the [`examples`](https://github.com/segmentio/terraform-docs/tree/master/examples) folder, specifically [doc.adoc](https://github.com/segmentio/terraform-docs/blob/master/examples/doc.adoc) or [doc.md](https://github.com/segmentio/terraform-docs/blob/master/examples/doc.md) or [doc.txt](https://github.com/segmentio/terraform-docs/blob/master/examples/doc.txt) you'd see none of them are wrapped in any sorts of comments. And you can simply run

```bash
terraform-docs markdown table --header-from doc.txt ./examples/
```

which extracts the module header from those files. I'd suggest to download the latest [release](https://github.com/segmentio/terraform-docs/releases) or build `HEAD` of master and give it another try and update this issue if you still fave the problem.

**Comment by vFondevilla** [comment]
Yes, same issue here with the v0.9.1.

**Comment by khos2ow** [comment]
Release [`v0.10.0-rc.1`](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.10.0-rc.1) has been cut, can you give it a try on it?

Also please take a look at the corresponding section in usage guide ([here](https://github.com/terraform-docs/terraform-docs/blob/master/docs/USER_GUIDE.md#generate-module-header)) to see if there's something missing there.
