### ISSUE TITLE
Add support to document referenced resource types

### ISSUE THREAD

**Issue by aaronsteers** [terraform-docs/terraform-docs#287]
**Is your feature request related to a problem? Please describe.**

I want to expose module and resource dependencies in a similar way as declared providers are documented. 

**Describe the solution you'd like**

Two new optional sections would be added:

```
## Resource types used:

- `aws` provider resources:
  - `aws_instance`
  - `aws_iam_role`
```

and 

```
## External modules referenced:

- `tableau-server`
  - local alias: `my_tableau_server`
  - source: https://github.com/slalom-ggp/dataops-infra/tree/main/catalog/aws/tableau-server
  - version reference: `master`
- ...
```

**Describe alternatives you've considered**

I'm looking into doing this in a separate codebase but I'd rather not maintain it myself.

**Additional context**

As I create large module libraries, I want people to be able to better understand how those modules are composed, and what interdependencies exist between modules.

I'm happy to help contribute to the feature if approved.

**Follow-up Question**

Can anyone point me to the part of the code which performs parsing, plus perhaps a little info if all of the parsing is performed by this library versus calling on another library/tool to perform that? The way I picture this working is either via regex or by parsing the output of `terraform graph` or similar too - I'm not sure which, but if coming from another tool, we'd of course need to confirm that the desired info is contained within that tool's output.

**Comment by aaronsteers** [comment]
I think I found where source is parsed - is it here (https://github.com/segmentio/terraform-docs/blob/357610bb383c8d1c83a9c3b1186cdb65d7b83c25/internal/tfconfig/load_hcl.go)? 

And I do already see module defs being processed - which is a surprise - can someone confirm?

**Comment by xortim** [comment]
I started working on this here: https://github.com/terraform-docs/terraform-docs/compare/master...xortim:resource-list

**Comment by khos2ow** [comment]
That is awesome @xortim! Would you mind opening a PR for it to have a place to review and potential further discussions?

**Comment by nitrocode** [comment]
Thanks for the suggestion @aaronsteers. I like this idea a lot so i don't have to go to the terraform registry for this information.

@xortim nice work on the PR. I'm looking forward to seeing the changes merged.

I wasn't sure if this ticket was scope creep or should be a part of this ticket as well. Please ignore this if it should be separated
 I created this for now regarding outputted modules. 

https://github.com/terraform-docs/terraform-docs/issues/287

**Comment by khos2ow** [comment]
@aaronsteers would you please open another ticket to keep track of modules documentation? Specifically because #347 only partially addresses this issue and I'd like to be able to close this as soon as we merge that one.

**Comment by aaronsteers** [comment]
> @aaronsteers would you please open another ticket to keep track of modules documentation? Specifically because #347 only partially addresses this issue and I'd like to be able to close this as soon as we merge that one.

Created here: #365 

NOTE to watchers, if you want to follow the module dependencies request, please make sure to add a thumbs up on #365.
