### ISSUE TITLE
Unable to install from proxy.golang.com

### ISSUE THREAD

**Issue by lukestanbra** [terraform-docs/terraform-docs#291]
**Describe the bug**

The go.mod metadata stored in proxy.golang.org uses the `module github.com/segmentio/terraform-docs` instead of `module github.com/terraform-docs/terraform-docs`; this makes it impossible to use this proxy to install the module.

**To Reproduce**

1. `go clean --modcache`
2. `export GOPROXY=https://proxy.golang.org`
3. `go get github.com/terraform-docs/terraform-docs`

Do you have long logs to share? Please go to https://ghostbin.com and
insert the link here.

**Expected behavior**

The module should install

**Actual behaviour**

```
go get: github.com/terraform-docs/terraform-docs@v0.9.1: parsing go.mod:
	module declares its path as: github.com/segmentio/terraform-docs
	        but was required as: github.com/terraform-docs/terraform-docs
```

**Version information:**

- terraform-docs version (use `terraform-docs --version`): v0.9.1
- Go version (if you manually built. use `go version`): go version go1.14.4 darwin/amd64
- OS (e.g. Windows, MacOS): MacOs

**Additional context**

I'm not sure whether this is actually something you are in control of or not, but thought I'd let you know anyway.

**Comment by khos2ow** [comment]
Thank you for reporting. This is in fact an issue of migration to the new organization. I will update the doc for the workaround. If you want to download anything **before** `v0.9.1` (inclusive) you need to use `segmentio` module organization:

```bash
go get github.com/segmentio/terraform-docs@v0.9.1
```

but for anything **after** `v0.10.0` (inclusive) you need to use new `terraform-docs` module organization:

```bash
go get github.com/terraform-docs/terraform-docs@v0.10.0

# or as of the time of writing this

go get github.com/terraform-docs/terraform-docs@v0.10.0-rc.1
```

**Comment by lukestanbra** [comment]
This worked, thanks very much :)
