### ISSUE TITLE
config file options not present

### ISSUE THREAD

**Issue by derekmurawsky** [terraform-docs/terraform-docs#292]
I ran the latest docker container using `docker run quay.io/terraform-docs/terraform-docs` with the -c option and it errored with `Error: unknown flag: -c`

I then downloaded the latest release, terraform-docs-v0.9.1-linux-amd64, and had the same issue. 

**To Reproduce**

1. Download the latest release
2. Try running with the -c or --config-file options
3. It will error

**Expected behavior**

It should read the configuration file per the documentation here: https://github.com/terraform-docs/terraform-docs/blob/master/docs/CONFIG_FILE.md

**Comment by khos2ow** [comment]
Option for config has been added in `v0.10.0` which is still in release candidate mode, you can:

- use docker tag `edge` which is equivalent to HEAD of `master` (as opposed to docker tag `latest` which represents the _latest_ official release)
- download the `v0.10.0-rc.1` binary from [release page](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.10.0-rc.1)

**Comment by derekmurawsky** [comment]
I just saw that when I looked into releases. I would suggest making the documentation clearer in that regard. Thank you for a great tool!

**Comment by khos2ow** [comment]
Yes our documentation needs some more love!
