### ISSUE TITLE
Is there an equivalent tool for building the README.md for a provider written in Go?

### ISSUE THREAD

**Issue by rquadling** [terraform-docs/terraform-docs#301]
Looking to be able to use a provider (https://github.com/Mastercard/terraform-provider-restapi) but it needs some small amount of work for getting it into the registry.

One part is the documentation. And so, considering how good pre-commit-terraform gets things done via terraform-docs for terraform scripts, I was wondering if there is an equivalent tool for working on a terraform provider written in Go.

I'm not a Go developer, so that's why I'm looking for some automation on this.

**Comment by khos2ow** [comment]
Apologize for late response. I'm not aware of such a tool and to be honest I don't think it exists. My best suggestion at the moment is to reach out directly to Terraform team over at @hashicorp. They do have specific guideline on how to write and implement a provider which covers so many things except how to generate the docs (not sure if they recently added something on that regard or no).

**Comment by rquadling** [comment]
There is an, as yet, unreleased tool which should do the work on this from them. Waiting to see if there is any movement.

Thank you.
