### ISSUE TITLE
Adjust output format for headers for markdown

### ISSUE THREAD

**Issue by Olgoetz** [terraform-docs/terraform-docs#302]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

It would be nice to have a yaml section to configure the heading size of requirements, providers etc. Currently it is set for markdown to h2 (##). 

**Describe alternatives you've considered**

Manual rework on the output text.

**Additional context**

n/a

**Comment by khos2ow** [comment]
Apologize for the late response. You can do this with `--indent int` flag on CLI or the following in `.terraform-docs.yml` file:

```
settings:
  indent: <int>
```

Note that either of the ways above only work when generating a `markdown` or `asciidoc` output.

**Comment by khos2ow** [comment]
@Olgoetz is this issue still relevant?

**Comment by Olgoetz** [comment]
No, solved.
