### ISSUE TITLE
Optionally add an "autogenerated" warning comment in markdown mode

### ISSUE THREAD

**Issue by wlonkly** [terraform-docs/terraform-docs#309]
**Is your feature request related to a problem? Please describe.**

Sometimes, folks working on a repo don't realize that the README is generated by terraform-docs, and they edit the file in place. 

**Describe the solution you'd like**

In markdown mode, I'd like `terraform-docs` to (optionally) add a comment to the top of the generated doc, like

```
<!-- Autogenerated by terraform-docs. Do not modify this file directly. -->
```

(or something user-specifiable, so that it's not limited to English-speakers maybe.)

**Describe alternatives you've considered**

Any other approach means putting the comment in the _source_, which defeats the purpose, because people should modify the source!

**Comment by khos2ow** [comment]
After a bit of thinking over this and #322 I think I'll like to take the following approach:

```
      --notice                  show notice message (default: true)
      --notice-message string   notice message to inject (default:  Autogenerated by terraform-docs. Do not modify this file directly.)
      --notice-position sting   position to place notice message [top, bottom] (default: top)
      --notice-comment          show notice as invisible comment or visible text (default: true)
```

@wlonkly @alexjurkiewicz what do you all think?

**Comment by alexjurkiewicz** [comment]
For my use it's overkill. A hardcoded string is more than enough. It just
needs to prompt a newbie to our docs "hey, don't edit this file, ask if you
can't figure out the source". But maybe you have other use cases in mind
too, that's just me!

**Comment by wlonkly** [comment]
I'd be happy with the first two options and wouldn't care about the second two. Being able to override the message is important for non-English speakers I think, even though I wouldn't use it myself. Can't think of any time I'd want it at the bottom.

Hm, you could get rid of the need for --notice-comment by leaving it up to the user to add the comment characters to their notice message (and defaulting notice-message to having the comment characters).

**Comment by khos2ow** [comment]
@alexjurkiewicz I see your point, but terraform-docs is being used by a broader audience and if we want to introduce a new feature we should take that into consideration that some folks might not want to use it or use it in a different way than the others. That said, having it hardcoded in the code will defeat this purpose and will break some workflows for some folks.

**Comment by khos2ow** [comment]
@wlonkly

> Can't think of any time I'd want it at the bottom.

I thought about the position of notice to have a more flexibility to control it, and specially might be interesting if you want the notice to be visible (then it might look nicer to be at the bottom of the page rather than top of the document).

> leaving it up to the user to add the comment characters to their notice message

This is actually a pretty good idea! :+1:

**Comment by khos2ow** [comment]
Following up after #425, I think this issue and also #322 are not needed any more, as it can be baked into the template on each individual use-case. For example the following `.terraform-docs.yml` configuration:

```yaml
formatter: markdown table
output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    <!-- Autogenerated by terraform-docs. Do not modify this file directly. -->

    {{ .Content }}
    <!-- END_TF_DOCS -->

settings:
  indent: 2
```

will produce the following `README.md`:

```makrdown
# Module

Any arbitrary content in README
...

<!-- BEGIN_TF_DOCS -->
<!-- Autogenerated by terraform-docs. Do not modify this file directly. -->
...

## Requirements
...

## Providers
...

...
<!-- END_TF_DOCS -->

Continue arbitrary content of README.
```

Please let us know if you have any questions, comments, or suggestions.

**Comment by khos2ow** [comment]
@wlonkly @alexjurkiewicz how do y'all think about my suggestion above?

**Comment by mkatneni** [comment]
```cat .tfdocs-config.yml
formatter: markdown table
output:
  file: README.md
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    <!-- Autogenerated by terraform-docs. Do not modify this file directly. -->

    {{ .Content }}
    <!-- END_TF_DOCS -->

settings:
  indent: 2```

This is how my config file looks but the generated output is not replacing the README just standard out what am I missing here and also I don't see this printed at the top `Autogenerated by terraform-docs. Do not modify this file directly. `

**Comment by khos2ow** [comment]
It looks like you're using an older version of terraform-docs, [saving content directly into file](https://terraform-docs.io/user-guide/how-to/#insert-output-to-file) has been added in [v0.12.0](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.12.0). Can you please upgrade and try again?

**Comment by mkatneni** [comment]
Thanks that helped

**Comment by khos2ow** [comment]
Going to close this issue as it seems it's working with using of template.
