### ISSUE TITLE
Automatically include example in readme

### ISSUE THREAD

**Issue by bostrowski13** [terraform-docs/terraform-docs#313]
Like most people, we use the "examples" folder to store practical examples of how to use thoe module.  However, it would be great if this made it into the documentation automatically when running terraform-docs.

We use the feature where we use the documentation block at the top of a TF File, which presently includes the example(s), to include in the readme.me, but it would be nice only to touch the example itself and have it included without having to maintain in both places.

I would say much like variables and outputs are pulled in, I'd like to be able to pull in the example(s) as well.

**Comment by khos2ow** [comment]
dup: #286

**Comment by khos2ow** [comment]
As I mentioned https://github.com/terraform-docs/terraform-docs/issues/378#issuecomment-839238642, we can have this one implemented soon.

**Comment by bostrowski13** [comment]
Thank you!
