### ISSUE TITLE
Variable default of "<" is transformed to "\u003e" in markdown

### ISSUE THREAD

**Issue by nairb774** [terraform-docs/terraform-docs#314]
**Describe the bug**

The tool looks to be over-escaping the defaults of variables when generating markdown.

**To Reproduce**

1. Define a variable like:
    ```terraform
    variable "monitor_operator" {
      description = "query operator"
      type        = string
      default     = ">"
    }
    ```
2. Run the tool like:`terraform-docs markdown --sort-by-required .`
3. Observe the output in the table has the following contents:
    ```markdown
    | monitor\_operator | query operator | `string` | `"\u003e"` | no |
    ```

**Expected behavior**

Ideally the default value would render faithfully. For Github, when wrapped in backticks, it seem to not require any escaping. Something like the following should render correctly:

```markdown
| monitor\_operator | query operator | `string` | `"<"` | no |
```

**Version information:**

- terraform-docs version (use `terraform-docs --version`):
```
$ terraform-docs --version
terraform-docs version v0.0.0- v0.9.1 darwin/amd64 BuildDate: 2020-04-03T02:30:49+0100
```
- Go version (if you manually built. use `go version`): Installed via homebrew.
- OS (e.g. Windows, MacOS): macOS

**Comment by khos2ow** [comment]
This has been fixed in #284
