### ISSUE TITLE
Consider more frequent releases

### ISSUE THREAD

**Issue by cah-andrew-fitzgerald** [terraform-docs/terraform-docs#315]
**Is your feature request related to a problem? Please describe.**

I would like to be able to use features that have been present in master for several months.

**Describe the solution you'd like**

More frequent releases of terraform-docs.

**Describe alternatives you've considered**

We could build terraform-docs locally, but most of our usage is manual making it difficult to synchronize versions across developers.

**Additional context**

Love the project.  I've been keeping an eye out for a new release so I could use https://github.com/terraform-docs/terraform-docs/pull/252 for a couple months now, would be nice if the release cadence was a bit faster.

**Comment by khos2ow** [comment]
You are absolutely correct and I apologize for the delay. I'll try to keep up the pace more.

**Comment by khos2ow** [comment]
I'm going to close this one. We're trying to adhere to 4-5 weeks release cadence.
