### ISSUE TITLE
Error: accepts 1 arg(s), received 0

### ISSUE THREAD

**Issue by edbizarro** [terraform-docs/terraform-docs#324]
**Describe the bug**

After upgrading to 0.10 an error appears `Error: accepts 1 arg(s), received 0`

**Version information:**

- terraform-docs version (use `terraform-docs --version`): `terraform-docs version v0.10.0 5a922ad linux/amd64 BuildDate: 2020-09-21T19:01:40+0000`
- OS (e.g. Windows, MacOS): Arch

**Additional context**

**Comment by khos2ow** [comment]
Can you provide the exact command you executed that resulted in that error?

**Comment by khos2ow** [comment]
@edbizarro do you still have this issue on `v0.10.0` or `v0.10.1`?

**Comment by aidan-melen** [comment]
Hey @khos2ow, I was able to reproduce @edbizarro issue and here are the steps.

**Comment by aidan-melen** [comment]
For what it is worth. `terraform-docs` works as expected when you have the executable running natively. e.g.

```
$ brew install terraform-docs
$ terraform --verison
terraform-docs version v0.0.0- v0.10.1 darwin/amd64 BuildDate: 2020-09-29T01:18:38+0100

$ terraform-docs markdown .                                                                                                                                                                                                               HEAD
## Requirements

| Name | Version |
|------|---------|
| terraform | >= 0.13.0 |
| aws | >= 2.70.0 |

## Providers

| Name | Version |
|------|---------|
| aws | >= 2.70.0 |

## Inputs

| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| ec2\_instance\_type | AWS EC2 instance type. | `string` | `"t2.small"` | no |

## Outputs

| Name | Description |
|------|-------------|
| instance\_id | EC2 instance id |
```

setup `.pre-commit-config` to use local executable of `terraform-docs`

```yaml
# .pre-commit-config.yaml
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.43.0
  hooks:
    - id: terraform_docs
```

and that also works

```bash
pre-commit run
Terraform docs...........................................................Passed
```

but I did notice this error when incorrectly passing arguments to `terraform-docs`

**Comment by aidan-melen** [comment]
I can see that you migrated to `cobra` for handling the cli. I will take a quick peak.

**Comment by khos2ow** [comment]
@edbizarro @aidan-melen can you provide a bit of update here? Is this issue still happening?

**Comment by edbizarro** [comment]
> @edbizarro @aidan-melen can you provide a bit of update here? Is this issue still happening?

It's working now :D

**Comment by khos2ow** [comment]
Awesome, thanks. I'll go ahead and close this ticket then.
