### ISSUE TITLE
version management using e.g. .terraform-docs-version file or extension to .terraform-docs.yml

### ISSUE THREAD

**Issue by tbugfinder** [terraform-docs/terraform-docs#343]
**Is your feature request related to a problem? Please describe.**

Within projects version constraints for e.g. ruby (.ruby-version) or terraform (tfenv / .terraform-version) and many others can be defined. I'm wondering if such a feature could be included in `.terraform-docs.yml` or if we should rather have an external tooling (based e.g. on tfenv https://github.com/tfutils/tfenv) managing such a constraint.

**Describe the solution you'd like**

Define a version constraint within the given project folder and automatically use this version to run `terraform-docs`.

**Describe alternatives you've considered**

It depends. Obviously a spin-off of tfenv to e.g. tfdocsenv sounds reasonable.

**Additional context**

**Comment by khos2ow** [comment]
Thanks @tbugfinder, I like the idea of having a version constraint defined in `.terraform-docs.yml` not as a mechanism to download that version but rather for enforcing that correct version of terraform-docs binary is being used at the time of execution and flat out reject processing if there's a version violation.

That being said, at the moment, I cannot think of a good reason why one would need this. I mean we don't have hard backward incompatibility or something in that nature that forces user to use one specific version over the other. Have you faced such a scenario that you had to use one version or needed to enforce one?

**Comment by tbugfinder** [comment]
Hi @khos2ow ,
indeed we use terraform-docs within multiple terraform module repos. Those repos have different released versions and may depend on a different terraform-docs version during the modules released versions.
Indeed some CLI changes of 0.8.x compared to 0.10.x break use of a single terraform-docs version on all module releases. Therefore it would be helpful if terraform-docs could at least support a version constraint.
