### ISSUE TITLE
Support accentuated characters

### ISSUE THREAD

**Issue by kinwolfqc** [terraform-docs/terraform-docs#348]
**Is your feature request related to a problem? Please describe.**

Right now, when terraform-docs encounter accentuated character, it cannot deal with them correctly. 

**Describe the solution you'd like**

We'd like the support of accentuated character so the docs can actually be readable :P
 Here is an example:
tfdocs output:
```
| location | R├®gion ou sera d├®ploy├®e les ressources | `string` | `"US East"` | no |
```
expected output
```
| location | Région ou sera déployée les ressources | `string` | `"US East"` | no |
```

**Comment by khos2ow** [comment]
@kinwolfqc sorry for very delayed response. I just tried with following and wasn't able to reproduce the issue.

```
variable "accent" {
  type    = "string"
  default = "Région ou sera déployée les ressources"
}
```

Can you verify you still have the issue on latest from HEAD of master or latest docker image?

**Comment by kinwolfqc** [comment]
Indeed, I didn't noticed that it got fixed somehow since I was avoiding accentuated for the moment.
All working fine now, thanks!

**Comment by khos2ow** [comment]
Awesome, thanks!

**Comment by kinwolfqc** [comment]
Hi, I downloaded version 0.13 and I have the accentuated problem once again.  Here is the code, and the result which end up as 

`cl├® primaire pour se connecter aux services cognitifs `:

```
output "primary_access_key" {
  description = "clé primaire pour se connecter aux services cognitifs"
  value       = azurerm_cognitive_account.primary_access_key
}

output "secondary_access_key" {
  description = "clé secondaire pour se connecter aux services cognitifs"
  value       = azurerm_cognitive_account.secondary_access_key
}
```


```
| Name | Description |
|------|-------------|
| <a name="output_primary_access_key"></a> [primary\_access\_key](#output\_primary\_access\_key) | cl├® primaire pour se connecter aux services cognitifs |
| <a name="output_secondary_access_key"></a> [secondary\_access\_key](#output\_secondary\_access\_key) | cl├® secondaire pour se connecter aux services cognitifs |
```

**Comment by kinwolfqc** [comment]
reclosing this, I found that the problem is with powershell that screw the accent when redirecting to a file.  Works fine in a cmd shell.  Specifying the encoding to powershell doesn't solve the issue, but it's not this tool problem :P

**Comment by khos2ow** [comment]
Awesome, glad to hear!

**Comment by diyfr** [comment]
@khos2ow 
- Same problem on Windows  
**terraform-docs version v0.16.0 1f686b1 windows/amd64**  
- No problem with same project, same files on linux (WSL)   
**terraform-docs version v0.16.0 1f686b1 linux/amd64**  

Terraform files charset : **UTF8**
