### ISSUE TITLE
Alone bold line formatting is escaped with markdown document 

### ISSUE THREAD

**Issue by gpascual4qima** [terraform-docs/terraform-docs#351]
**Describe the bug**
Using the output markdown document, I have an issue with alone bold line formatting. The `*` character is always escaped during generation.
 
**To Reproduce**

1. Create a module with a main.tf
2. Put those lines in main.tf:
```
/**
* **Please, read this line before starting**
*/
```
3. Run `terraform-docs markdown . > README.md` in module folder 
4. Content of README.md:
```markdown
\*\*Please, read this line before starting\*\*
```

**Expected behavior**

```markdown
**Please, read this line before starting**
```

**Version information:**

- terraform-docs version: 0.10.1
- OS: Ubuntu

**Comment by gpascual4qima** [comment]
After having investigating, I found something. Why do I need to add `--escape=false` to solve this behaviour?

**Comment by mengesb** [comment]
This also happens with a `header-from: [FILE]` as well.

**Comment by khos2ow** [comment]
Originally we included `*` in illegal characters to be escaped, specifically when formatter is markdown or asciidoc, and #179 fixed almost all of the use-cases except the one mentioned here (i.e. this regex `^(\*+)(.*)(\*+)$` - one bold line).

But now, to be honest, I don't see a point of doing that anymore. I'll open a PR for this shortly.
