### ISSUE TITLE
Add option to add footer as well as header

### ISSUE THREAD

**Issue by simonc-613** [terraform-docs/terraform-docs#368]
**Describe the solution you'd like**

Add option for a footer section similar to the headers section which comes after the inputs/outputs etc.

**Describe alternatives you've considered**

I've considered using the header but there are some things I wish to document in a README.md (contributing, versioning etc) which i feel is less important than the actual generated docs and should come after

**Comment by gmbdog** [comment]
I would second this request.  We like to append disclaimers/copyright strings at the end of documentation files, this would make it super simple.

**Comment by khos2ow** [comment]
This is great, thank you for the suggestion!

**Comment by simonc-613** [comment]
I started work on this this afternoon.
Need to work through the tests next week and then will push up and raise a PR

**Comment by si-c613** [comment]
Quick update on this, I've pushed my branch but there are a lot of files changed and I wasn't really sure I could refine it by commits much more really (a lot of new test files)
https://github.com/terraform-docs/terraform-docs/compare/master...si-c613:368-Add-Footer-Option?expand=1

I'm just wrestling with a rebase cause there have been a lot of changes to the codebase which have either conflicted or caused issues with renamed functions etc I'm trying to unpick

**Comment by si-c613** [comment]
The biggest issue so far is the change to use the plugin-sdk for print as this doesn't support `.settings.ShowFooter` in the template as it is now brought in by dependency.
Will have to look at getting the SDk updated in order to progress this

**Comment by khos2ow** [comment]
@si-c613 unfortunately that's in the core of this repo and there are a lot of common test files being modified for each feature which causes a conflict for other PRs. I'd suggest to open your PR as is to have a place for review and follow up discussion and note that you don't need to fix the conflicts right away (since there's another PR will be getting merged soon which will cause the conflict no matter what)

**Comment by si-c613** [comment]
Thanks @khos2ow , appreciate the heads up and the changes going on.

I've raised a draft PR to start any conversations required in advance of fixing merge conflicts/changes for refactors.

Also now that I've seen the codebase I think I will raise a separate feature request for the possible alternatives to have a Go Template format to allow custom formatting (I haven't yet checked to see if such a feature request already exists)
