### ISSUE TITLE
Non deterministic output when datas and resources have same name

### ISSUE THREAD

**Issue by ripa1993** [terraform-docs/terraform-docs#393]
### Describe the bug

I'm running terraform-docs via a pre-commit hook on a Terraform project containing Azure resources. I have observed a non deterministic README.md rendered when there are resources and datas with same name:

<img width="951" alt="Schermata 2021-02-15 alle 16 21 02" src="https://user-images.githubusercontent.com/5972762/107965933-74869580-6fab-11eb-9c13-bf6e6aed2753.png">

and then

<img width="938" alt="Schermata 2021-02-15 alle 16 35 20" src="https://user-images.githubusercontent.com/5972762/107966222-d515d280-6fab-11eb-9318-026b8d39b279.png">

Will it be solved by #392 ?

### How can we reproduce it?

It happens for example when using

```hcl
data "azurerm_dns_zone" "parent" {
  name                = var.external_domain
  resource_group_name = var.parent_resource_group_name
}

resource "azurerm_dns_zone" "this" {
  name                = "${var.prefix}.${var.external_domain}"
  resource_group_name = var.resource_group_name

  tags = var.tags
}
```

### Environment information

- terraform-docs version: `v0.11.0 darwin/amd64 BuildDate: 2021-02-11T00:17:03+0000`
- Go version: `go1.15.6 darwin/amd64`
- OS: macOS 11.2.1

**Comment by bashims** [comment]
@ripa1993 #392 definitely solves the issue for us.

**Comment by bryantbiggs** [comment]
@khos2ow would it be possible to release this in a patch release (i.e. - `v0.11.1`)?

**Comment by khos2ow** [comment]
@bryantbiggs yes definitely!

**Comment by antonbabenko** [comment]
@khos2ow Thanks for the upcoming 0.11.1 release! 🚀
