### ISSUE TITLE
Sort order of resources is not consistent between MacOS and Debian 

### ISSUE THREAD

**Issue by i-n00b** [terraform-docs/terraform-docs#400]
### Describe the bug

The sort order of resources in the Resources section is different on Linux and Mac

### How can we reproduce it?

Create a Terraform file with the following resources:
```
resource "google_kms_crypto_key" "gke_key" {}

resource "google_kms_crypto_key_iam_member" "grant-service-encrypt-decrypt" {}

```
Run `terraform-docs markdown document ./gke-cluster --sort=false`

On MacOS, output is:
```
## Resources

The following resources are used by this module:

- [google_kms_crypto_key](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/kms_crypto_key)
- [google_kms_crypto_key_iam_member](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/kms_crypto_key_iam_member)
```

On Debian, output is:
```
The following resources are used by this module:

- [google_kms_crypto_key_iam_member](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/kms_crypto_key_iam_member)
- [google_kms_crypto_key](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/kms_crypto_key)
```

### Expected output
1. The outputs should be consistent.
2. Because the flag `--sort=false` is set, the resources should be listed in the order in which they appear

### Environment information

- terraform-docs version: v0.11.1
- OS: MacOS, Debian

**Comment by khos2ow** [comment]
Hmm, that's very strange. We always sort resources for consistency irrelevant of `--sort=false`. And the fact that the behavior is not the same on different platforms is as much strange.

https://github.com/terraform-docs/terraform-docs/blob/486c9ce05e8b980248fb6b5106ed31bb80a9efe2/internal/terraform/module.go#L470-L471

Is this something that you can consistently reproduce? Do you see this behavior if you keep running terraform-docs only on one of those, e.g. only Debian?

**Comment by i-n00b** [comment]
I apologize for creating this bug. The `terraform-docs` version on my Mac was v0.11.0. On upgrading to v0.11.1, the issue got resolved.

**Comment by khos2ow** [comment]
Awesome, good to hear! 👍
