### ISSUE TITLE
Anchor support for resources, modules, inputs, outputs, etc

### ISSUE THREAD

**Issue by nitrocode** [terraform-docs/terraform-docs#408]
### What problem are you facing?

I cannot link to a specific variable in the markdown.

### How could terraform-docs help solve your problem?

I'd like each variable to have an anchor associated with it so I can right click, copy link, and share it with someone.

We can do this with the official terraform docs for [resource arguments](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#transit_encryption_enabled) but not module inputs on hashicorp registry or from terraform-docs.

Here is an [example in markdown from Stackoverflow](https://stackoverflow.com/a/7335259/2965993) of a way to put anchors in markdown

Here is an [example of the outputted anchors](https://gist.github.com/nitrocode/4de07fd583ac864b1d871634c890cc8d#inputs_unquoted) from `table-WithRequired.golden`

I propose anchors prefixed with their section name

* `resources_`
* `modules_`
* `inputs_`
* `outputs_`
* `providers_`

I'm mostly interested in the markdown output since that affects all the git repos. Would we want to do this for other output types as well ? or could that wait for a follow up PR ?

**Comment by khos2ow** [comment]
Thanks @nitrocode, this is a really good suggestion! The only drawback I can think of is that we're going to mix raw html and markdown and any editor and markdown linter would not be happy about this and will show tons of warning messages.

That being said, I'd like to hear more from folks to see if anyone objects and we might want to potentially add an off-switch for this.

**Comment by nitrocode** [comment]
Oh I didn't think that could be an issue. I'll look into adding that a switch this weekend.

**Comment by nitrocode** [comment]
As for `markdownlint` messages

```bash
$ wget https://gist.githubusercontent.com/nitrocode/4de07fd583ac864b1d871634c890cc8d/raw/table-WithRequired.md
$ markdownlint table-WithRequired.md 2>&1 | cut -d' ' -f2 | sort | uniq -c
      2 MD004/ul-style
     36 MD013/line-length
     45 MD033/no-inline-html
      1 MD034/no-bare-urls
      1 MD041/first-line-heading/first-line-h1
      1 MD047/single-trailing-newline
```

* `MD033/no-inline-html` is flagged due to this change
* `MD013/line-length` has probably has increased. Not sure how to lower the length of each line as that would break the table.

By adding the following to the top of the outputted markdown, we can disable those rules from applying but maybe that's not something that should be done.

```html
<!-- markdownlint-disable MD013 -->
<!-- markdownlint-disable MD033 -->
```

```markdown
✗ markdownlint table-WithRequired.md.ignore 2>&1 | cut -d' ' -f2 | sort | uniq -c
      2 MD004/ul-style
      1 MD034/no-bare-urls
      1 MD041/first-line-heading/first-line-h1
```
