### ISSUE TITLE
Refactor test suites for ease of contribution

### ISSUE THREAD

**Issue by khos2ow** [terraform-docs/terraform-docs#410]
### What problem are you facing?

Currently if a contributor wants to change or add a functionality they would need to change massive number of `.golden` files in order to tests pass. This is really counterintuitive and redundant in most cases, it also causes a lot of conflicts when rebasing on main branch.

### How could terraform-docs help solve your problem?

Refactor test suites in a way that the target of each test function focuses on that particular area and eventually reduce blast radius of changes in tests.

**Comment by nitrocode** [comment]
Hi @khos2ow thanks for working on this as it will be much easier to contribute changes. I hope I don't sound too eager, just wondering, when do you think this will be PRed ?

**Comment by khos2ow** [comment]
@nitrocode just opened #411 which should address this.
