### ISSUE TITLE
Add types column in the resources table

### ISSUE THREAD

**Issue by nitrocode** [terraform-docs/terraform-docs#412]
### What problem are you facing?

It's confusing when you see the following:

```
aws_iam_role
aws_iam_role
```

and then you have to mouse over each one to see which one to click on to get the resource docs.

### How could terraform-docs help solve your problem?

I'd like a similar `types` column for the resources table. 

Similar issue to https://github.com/terraform-docs/terraform-docs/issues/269

Perhaps the `Resource.Mode` can be used within the template itself.

https://github.com/terraform-docs/terraform-docs/blob/dc26188944178288e707d7325aadb4223b643a12/internal/terraform/resource.go#L38-L50

We could check `Mode` and set the type `managed => resources` and `data => data` 😄 in the [resource](https://github.com/terraform-docs/terraform-docs/blob/master/internal/format/markdown_table.go#L30-L47) template

**Comment by edgarsandi** [comment]
Hi all! Can I work on this feature? Or someone already working?

**Comment by khos2ow** [comment]
Go for it @edgarsandi!

**Comment by edgarsandi** [comment]
I’m thinking about what is the best pattern to do, I write some suggestions to get your opinion:

---
#### Suggestion 1:

→ At the beginning inside the `<URL>` (as in the terraform registry, or at the end with format like ASCII document format for example)

→ Always sort by `<Mode>` (Data Source < Resource), then sort by `<ProviderName>_<Type>.<Name>`

- [Data Source: aws_iam_group.example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_group)
- [Data Source: aws_iam_user.example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_user)
- [Resource: aws_iam_access_key.lb](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/aws_iam_access_key)
- [Resource: aws_iam_user_policy.lb_ro](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user_policy)

---

#### Suggestion 2:

→ At the beginning with parentheses before `<URL>`

→ Always sort by `<Mode>` (Data Source < Resource), then sort by `<ProviderName>_<Type>.<Name>`

- (Data Source) [aws_iam_group.example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_group)
- (Data Source) [aws_iam_user.example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_user)
- (Resource) [aws_iam_access_key.lb](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/aws_iam_access_key)
- (Resource) [aws_iam_user_policy.lb_ro](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user_policy)

---

#### Suggestion 3:

→ At the end with parentheses after `<URL>`

→ Always sort by `<Mode>` (Data Source < Resource), then sort by `<ProviderName>_<Type>.<Name>`

- [aws_iam_group.example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_group) (Data Source)
- [aws_iam_user.example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_user) (Data Source)
- [aws_iam_access_key.lb](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/aws_iam_access_key) (Resource)
- [aws_iam_user_policy.lb_ro](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user_policy) (Resource)

---

#### Suggestion 4:

→ At the beginning inside the `<URL>` (as in the terraform registry, or at the end with format like ASCII document format for example)

→ Continue to sort by `<ProviderName>_<Type>_<Mode>.<Name>`

- [Resource: aws_iam_access_key.lb](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/aws_iam_access_key)
- [Data Source: aws_iam_group.example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_group)
- [Data Source: aws_iam_user.example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_user)
- [Resource: aws_iam_user_policy.lb_ro](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user_policy)

---

#### Suggestion 5:

→ At the beginning with parentheses before `<URL>`

→ Continue to sort by `<ProviderName>_<Type>_<Mode>.<Name>`

- (Resource) [aws_iam_access_key.lb](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/aws_iam_access_key)
- (Data Source) [aws_iam_group.example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_group)
- (Data Source) [aws_iam_user.example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_user)
- (Resource) [aws_iam_user_policy.lb_ro](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user_policy)

---

#### Suggestion 6:

→ At the end with parentheses after `<URL>`

→ Continue to sort by `<ProviderName>_<Type>_<Mode>.<Name>`

- [aws_iam_access_key.lb](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/aws_iam_access_key) (Resource)
- [aws_iam_group.example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_group) (Data Source)
- [aws_iam_user.example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_user) (Data Source)
- [aws_iam_user_policy.lb_ro](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user_policy) (Resource)

---

#### Suggestion n:

...

**Comment by nitrocode** [comment]
I'd say suggestion 2 because im more interested in resources than i am data sources, so i like how it's clearly sorted by type.

**Comment by khos2ow** [comment]
Thank you @edgarsandi for the great writeup. I like suggestion 3 better than 2. The main reason I think 3 works better than 2, is that when you want to skim through and find something (specially that items are sorted) in 2 the beginning of the words are not left-aligned and you have to horizontally move your eyesight (dozen pixels, but still!).

That said, I'd like suggestion 3 with a bit of modifications:

- `resource` instead of `Resource`
- `data source` instead of `Data Source`
- sorting "resources" before "data resources" (as they do have higher logical importance)

The bullet list should be used for `asciidoc document`, `markdown document`, and `pretty` formats. And for `asciidoc table` and `markdown table` the tabular version of it:


```text
| Name | Type |
|------|------|
| aws_iam_access_key.lb | Resource |
| aws_iam_user_policy.lb_ro | Resource |
| aws_iam_group.example | Data Source |
| aws_iam_user.example | Data Source |

// and the corresponding structure for "asciidoc table"
```
