### ISSUE TITLE
Support for populating cleaner version info from GitHub hosted modules

### ISSUE THREAD

**Issue by brettcurtis** [terraform-docs/terraform-docs#427]
### What problem are you facing?

We can't add a version constraint to modules we use from our GitHub Org.

For example:
```hcl
module "project" {
  source  = "git@github.com:my-org/terraform-google-project?ref=v2.1.2"
```

While we see it in the source column it's not as pretty as it could be :D 

### How could terraform-docs help solve your problem?

I'd like to see the end result look something like:
| Name | Source | Version |
|------|--------|---------|
| bridgecrew-read | bridgecrewio/bridgecrew-gcp-read-only/google | 0.3.6 |
| kubernetes_engine | my-org/terraform-google-project | v2.1.2 |

Love the project!

**Comment by khos2ow** [comment]
Thank you @brettcurtis for the very good suggestion! According to official [module source](https://www.terraform.io/docs/language/modules/sources.html) documentation there are multiple ways for defining source for the module, which in most of them concept of version doesn't apply. Specifically a version can be extracted from:

- Terraform Registry
- and any type of "Repository" if `?ref=<version>` is defined  (i.e. GitHub, BitBucket, Generic Git or Mercurial)

That is a very easy fix and we will definitely implement it, but, the notion of stripping out `github.com/` from modules hosted on GitHub might be a bit misleading. For example just by looking at `bridgecrewio/bridgecrew-gcp-read-only/google`, it's not immediately obvious that this is a repository on GitHub or a module in registry.terraform.io.

**Comment by brettcurtis** [comment]
No problem, thank you for the project! Yup, I agree. What might be useful is converting it to an actual URL. In our case we consume modules using SSH to GitHub vs. HTTP.  So it shows as:

| Name | Source | Version |
|------|--------|---------|
| bridgecrew-read | bridgecrewio/bridgecrew-gcp-read-only/google | 0.3.6 |
| kubernetes_engine | git@github.com:my-org/terraform-google-kubernetes-engine?ref=v2.0.0 |  |

So looking at it in the readme it's a clickable "email" address. Be cool if it would link directly to the repo in use and even the same for the standard registry module. I'm kinda scope creeping here but just an idea! :)

**Comment by khos2ow** [comment]
That's a good point. What about keeping the whole source as is (without stripping out `github.com/` from it) and try to extract the "actual" repository URL and make the source clickable. This potentially can be done for modules coming from github repository or Terraform registry itself.

**Comment by edgarsandi** [comment]
Hello guys! Can I work on this issue?

**Comment by khos2ow** [comment]
@edgarsandi sure, go for it! :+1:

**Comment by brettcurtis** [comment]
I also noticed if you're using the new version approach to providers you do not get a version from terraform-docs. https://www.terraform.io/docs/language/providers/configuration.html#provider-versions 

For example:
### Providers

| Name | Version |
|------|---------|
| google | n/a |

Happy to open another issue if ya want.

**Comment by khos2ow** [comment]
Yes please open another issue.

**Comment by edgarsandi** [comment]
Just as feedback on this issue, I'm still working on it.

I caught one problem: We've so many formats to define the source in terraform [(local, S3, SSH, HTTPS, registry, etc)](https://www.terraform.io/docs/language/modules/sources.html), that to separate the version from all these source formats (if it has support to version), isn't so trivial.

If anyone has a tip, will be very helpful.

**Comment by khos2ow** [comment]
I think we can ignore almost all of them except for Registry, and any Git related (github, bitbucket, etc). Concept of version doesn't really apply to the rest of them and we should report `n/a` for those.

That said, I'd suggest to draft a PR as is and we can take a closer look and to prevent redoing or overdoing things.
