### ISSUE TITLE
Add support for pre-commit

### ISSUE THREAD

**Issue by tpansino** [terraform-docs/terraform-docs#435]
### What problem are you facing?

As a user
I'd like to be able to run terraform-docs via a [`pre-commit`](https://pre-commit.com/) hook
So that I can easily add this to my existing hooks, use it as a check in a CI pipeline with [this GitHub Action](https://github.com/pre-commit/action), and so forth.

### How could terraform-docs help solve your problem?

By [adding hook support](https://pre-commit.com/#creating-new-hooks). 😄

**Comment by khos2ow** [comment]
Thank you @tpansino, I like the idea that we would provide a fully working pre-commit and if folks wanted more they can opt for other solutions out there!

**Comment by metmajer** [comment]
@khos2ow @antonbabenko and I previously worked on terraform-docs pre-commit hooks in the following repositories:

- https://github.com/metmajer/pre-commit-terraform
- https://github.com/antonbabenko/pre-commit-terraform

FYI @tbugfinder

**Comment by khos2ow** [comment]
@metmajer that's exactly what @tpansino mentioned on the PR as well

> I did find the existing instructions on how to use a Git hook, and the references to antonbabenko/pre-commit-terraform, but I wanted to provide a pre-commit hook here, on this repo, so that users don't require a second repo just to use this tool via pre-commit.

[antonbabenko/pre-commit-terraform](https://github.com/antonbabenko/pre-commit-terraform) is geared towards hooks for all the things Terraform, but this is limited only to terraform-docs, which IMO it's nice to have and will give users options.

**Comment by metmajer** [comment]
Got it @khos2ow. Seems like I missed that comment and posted these links only for transparency. Thanks @tpansino for contributing!
