### ISSUE TITLE
Ability to hide "Data sources" from the resource section

### ISSUE THREAD

**Issue by rprieto** [terraform-docs/terraform-docs#437]
Hi,

### What problem are you facing?

From a user's point of view, it can be confusing to see data source listed just as prominently as resources. 

- Some Terraform modules have more data sources than resources. In this case I think the long lists drowns the important information (what does this module create?).
- Some Terraform modules might use seemingly unrelated data sources (IAM Roles or VPC Endpoints) and people unfamiliar with Terraform Docs can be confused at first to see these AWS services listed under `Resources` (although they will then realise there is a "Type" column).

### How could terraform-docs help solve your problem?

I see the latest v0.12 beta shows whether an entry is a data source or an actual resource (https://github.com/terraform-docs/terraform-docs/issues/412). This is a very welcome addition.

My preference would have been for separate `Resources` and `Data sources` sections. This would give the ability to hide them based on the existing config flags.

Thank you!

**Comment by khos2ow** [comment]
Thank you @rprieto, that's a very good suggestion. I'm thinking we can add a new item to `--show/--hide datasources` to explicitly hide `Data sources` items. What do you think about this approach?

**Comment by rprieto** [comment]
Hi, that sounds perfect! It could either show/hide them from the existing `Resources` section, or manage the visibility of an independent `Data sources` section.

Personally I'd prefer the latter (Resources = only what the module creates).
