### ISSUE TITLE
Version 0.9.1 (possibly others) no longer works via docker

### ISSUE THREAD

**Issue by dmonaco05** [terraform-docs/terraform-docs#438]
Im not exactly sure what happened but older versions no longer function correctly which shouldnt happen as the docker image has not been changed.

Running from within the modules root dir:
`docker run quay.io/terraform-docs/terraform-docs:0.9.1 markdown .
`
returns:
```
## Requirements

No requirements.

## Providers

No provider.

## Inputs

No input.

## Outputs

No output.
```

### How can we reproduce it?
`docker run quay.io/terraform-docs/terraform-docs:0.9.1 markdown .
`

### Environment information
docker desktop 3.2.2 for mac
docker image v0.9.1
tf module v0.12.x

**Comment by khos2ow** [comment]
How do you pass the module folder into the container? Did you omit it here for brevity? otherwise `docker run -v $(pwd):/opt quay.io/terraform-docs/terraform-docs:0.9.1 md /opt` seems to be working.

**Comment by dmonaco05** [comment]
hmm odd maybe docker desktop removed automatic path mounting, that works locally now - just cant get it to work via pre-commit

**Comment by khos2ow** [comment]
Great! If by pre-commit you are referring to [this](https://terraform-docs.io/user-guide/how-to/#pre-commit-hook), note that it's just been added and will be fully released as part of `v0.12.0`. But in the meantime you can pass commit SHA (e.g. 0993f62f16a06b37eecb721762618020cf5429b5) to `rev` instead of a fixed version.

**Comment by dmonaco05** [comment]
pre-commit via https://github.com/antonbabenko/pre-commit-terraform

**Comment by dmonaco05** [comment]
either way not an issue with this project, thank you for helping me

**Comment by khos2ow** [comment]
No problem, please let us know if the issue was proven to be directly related to terraform-docs.
