### ISSUE TITLE
Allow customizing of generated sections `outputs`, `inputs`, `requirements`.

### ISSUE THREAD

**Issue by deepbrook** [terraform-docs/terraform-docs#442]
### What problem are you facing?
We're currently trying to build our tf documentation with the following `make` target:

```Makefile
TF_DOCS = docker run https:/harbor.eos.netrtl.com/quay.io/terraform-docs/terraform-docs:latest

.PHONY: docs
docs:
	$(TF_DOCS) md deploy --header-from=main.tf --show=header > ./deploy/README.md
	$(TF_DOCS) md deploy --header-from=inputs.tf --show=header >> ./deploy/README.md
	$(TF_DOCS) md deploy --show=inputs >> ./deploy/README.md
	$(TF_DOCS) md deploy --header-from=outputs.tf --show=header >> ./deploy/README.md
	$(TF_DOCS) md deploy --show=outputs >> ./deploy/README.md
```

We're procedurally generating our READMEs, in order to be able to prepend some up-front documentation/notes on inputs/outputs.

From the documentation of `terraform-docs` I can see there's a `config.outputs.template` option, but no useful information on what this template supports - specifically, what variables are available? I understand it's Go-templating, but that doesn't tell me much; I'm a rustacean/python programmer, so I'm lacking context here. I'm thus not sure I can use templating to make this work better.

Finally, there's always the problem of the generated section header, which typically clashes with our document structure (all section titles generated are `h1` if I'm not mistaken)

### How could terraform-docs help solve your problem?

I would expect terraform-docs to be smart about commonly used conventions: files such as `variables.tf`, `outputs.tf`, `versions.tf` etc. should have their headers autotmatically included in the relevant section's generated output.

I'll give an example to illustrate:

`main.tf`:
```terraform
/**
 * # My fancy module
 * ..does fancy things.
**/
```

`outputs.tf`
```terraform
/**
 *## Module Outputs
 * We expose data! 
**/
output "bar" {...}
```

`variables.tf`
```terraform
/**
 * ## Module Inputs
 * We like cake. And input variables. The latter are documented below.
**/
variable "foo" {...}
```

Running `terrform-docs md` should thus output the following:

```markdown
# My fancy module
..does fancy things.


## Module Inputs
We like cake. And input variables. The latter are documented below.

<insert table with inputs here>

## Module Outputs
We expose data!

<insert table with outputs here>
```

This behaviour could be toggled off/on with a flag, something like `--detect-section-headers` or similar.

The selection should also only happen, if the relevant terraform file name is present. I'd go with the suggested [best practices](https://www.terraform-best-practices.com/code-structure) on naming those (note that `versions.tf` is absent from this; however, since that was added by terraform's upgrade tool in previous versions, I think it's safe to assume it's a commonly used pattern).

**Comment by khos2ow** [comment]
> I can see there's a config.outputs.template option, but no useful information on what this template supports - specifically, what variables are available?

That's pretty much it. At the moment the template only contains one variable `{{ .Content }}` which is the whole output of a formatter execution (i.e. as if you run `terraform-docs md module` without a config file and to stdout.) But that's about it, to have control over what goes immediately before everything and after everything.

On the other hand you can consider building a [plugin](https://terraform-docs.io/developer-guide/plugins/) specific for your needs. Although that still doesn't solve for reading arbitrary _section_ header from file. (and the fact that currently it's only available to be written in go, although it's very minimal and should be easy to implement regardless of go knowledge)

> all section titles generated are h1 if I'm not mistaken

If I understood your point correctly, you do have control over this (with `settings.indent` in configuration), that controls the indention of heading (defaults to 2). For example:

```
.terraform-docs.yml
---
formatter: md tbl
settings:
  indent: 4
```

will generate:

```
#### Requirements
...

#### Providers
...

#### Inputs
...
```

> I would expect terraform-docs to be smart about commonly used conventions: files such as variables.tf, outputs.tf, versions.tf etc. should have their headers autotmatically included in the relevant section's generated output.

This is a very good suggestion, I'm gonna play around with the idea a bit to see if I find any strong argument for or against it.

**Comment by deepbrook** [comment]
>If I understood your point correctly, you do have control over this (with settings.indent in configuration), that controls the indention of heading (defaults to 2).

Ah, I misunderstood what that option does. Ok, great! That helps!

>On the other hand you can consider building a plugin specific for your needs. Although that still doesn't solve for reading arbitrary section header from file. (and the fact that currently it's only available to be written in go, although it's very minimal and should be easy to implement regardless of go knowledge)

I'll have a look into it. I'm thinking this might also be easily implemented by honoring the order of the `sections.show`/`--show` array configured by the user. I'll clock some time for this at work today.

**Comment by khos2ow** [comment]
> honoring the order of the sections.show/--show array configured by the user

This is an interesting, and a bit strange, idea! And definitely a bit hard to solve, and for what it's worth slightly outside of scope of this issue. But, definitely worth to be explored after we solved for #444 (specifically https://github.com/terraform-docs/terraform-docs/issues/444#issuecomment-806186465).

**Comment by khos2ow** [comment]
#503 potentially might be a fix for this one. Can you take a look at it and [corresponding](https://terraform-docs.io/user-guide/configuration/#content) docs?

I think you can have the following:

```yaml
# .terraform-docs.yml
header-from: main.tf

sections:
  show:
    - header
    - inputs
    - outputs

content: |-
  {{ .Header }}

  ## Module Inputs
  We like cake. And input variables. The latter are documented below.

  ( or alternatively {{ include "path/to/inputs/header.md" }} )

  {{ .Inputs }}

  ## Module Outputs
  We expose data!

  {{ .Outputs }}

settings:
  indent: 3
```

**Comment by khos2ow** [comment]
`content` will give you all the flexibility and it actually removes the need to implement, rather very complex, honoring order of `--show`.

**Comment by deepbrook** [comment]
@khos2ow Yup' that'll do the trick. Thanks!
