### ISSUE TITLE
Specifying `--show=<section>` results in error: `Error: '--show-all' and '--show' can't be used together`

### ISSUE THREAD

**Issue by deepbrook** [terraform-docs/terraform-docs#444]
Bug as the title says.

I would expect my explicitly set CLI flags to override the default.

At first I thought I had some rogue config file specifying `sections.show-all: true`, but running the following I was able to reproduce this issue consistently:

```bash
> mkdir -p test/module
> cd test
> echo "/**" >> module/main.tf
> echo " * # A Header" >> module/main.tf
> echo " * Something Written" >> module/main.tf
> echo "**/" >> module/main.tf
> ~/go/bin/terraform-docs md --show=header module
```

Update: out of curiosity, I created the following `.terraform-docs.yml` (and also found another bug - see #445):

```
# module/.terraform-docs.yml
---
sections:
  show-all: false
...
```

Running `~/go/bin/terraform-docs md --show=header module` after creating it works without issue.

Version output:
```bash
❯ ~/go/bin/terraform-docs --version
terraform-docs version 0.12.0 9c738b9 linux/amd64 BuildDate: 2021-03-22T18:50:22Z
❯ go version
go version go1.15.7 linux/amd64
```

Running on a Win10 WSL2 Ubuntu.

**Comment by khos2ow** [comment]
Maybe we need to update documentation for better clarity, but [here](https://terraform-docs.io/reference/terraform-docs/#options) specifically this, `--show-all` is enabled by default:

```
--hide-all                    hide all sections (default false)
--show-all                    show all sections (default true)
```

also from [here](https://terraform-docs.io/user-guide/configuration/#options) (first note below the config):

> Note: The following options cannot be used together:
>
>   - sections.hide and sections.show
>   - sections.hide-all and sections.show-all
>   - sections.hide-all and sections.hide
>   - sections.show-all and sections.show
>   - sort.by.required and sort.by.type

So when you run `terraform-docs md --show=header module`, conflicting instruction is being sent to terraform-docs, i.e. you're telling it to 1) show all sections and 2) show header (which is already being shown from previous instruction).

On the other hand you can do either of the following:

- `terraform-docs md --hide-all --show=header module`
- `terraform-docs md --show-all=false --show=header module`

Please let us know if this answers your question, and feel free to update the documentation!

**Comment by deepbrook** [comment]
Thanks @khos2ow for the quick reply!

I get that I, as a *user*, cannot state those options at their respective level at the same time. The documentation gets that across quite well.

However, If I tell `terraform-docs` to show me headers, it's really odd that a default setting gets in my way when I specify this specific behaviour.

In other words, I'd expect the following order of precedence (being used to this by pretty much any cli I can think of):

1. explicitly stated flags and options
2. explicitly stated configuration options
3. default cli flags and options values
4. default configuration option values

And therefore, if the user explicitly sets `--show`, `--hide-all` should be implicitly set by `terraform-docs`. Instead, it clashes with a default value, which imo, it should not.

Otherwise, you're saying it's common practice to have to double-check every default setting for possible conflicts with flags/options one would like to set. I cannot believe that this is by design and/or intentional, and would still classify this as a bug, as it's counter-intuitive.

**Comment by khos2ow** [comment]
That's a valid argument. Originally those flag pairs were intended to be explicitly called, but what you're suggesting is to make them implicitly assumed (which to be honest, it's a good idea anyways). But if we want to move forward with this suggestions I don't think there won't be any need for `--show-all` and `--hide-all` altogether.

In other words the definition (and documentation) can slightly be changed to:

```
--hide strings          hide specified section
--show strings          show only specified section
```

in which will allow for:

```
terraform-docs md --show header module                   # only show header
terraform-docs md --show header --show inputs module     # show header and inputs (and nothing else)

terraform-docs md --hide header module                   # only hide header
terraform-docs md --hide header --show inputs module     # hide header and inputs (but show everything else)

terraform-docs md --show header --hide inputs module     # error, --show and --hide should not be used together
```
