### ISSUE TITLE
`--config` option is always relative to the target path, not `$PWD`.

### ISSUE THREAD

**Issue by deepbrook** [terraform-docs/terraform-docs#445]
### Describe the bug
When giving the path to a configuration file, `terraform-docs` always preprends the target module's path.

Given:
```
~/tf/
  - module/
       - ...
  - .terraform-docs.yml
```
Running the following then results in an error:
```
~/tf/ > terraform-docs --config .terraform-docs.yml md module
Error: stat module/.terraform-docs.yml: no such file or directory
~/tf/ > terraform-docs --config ./.terraform-docs.yml md module
Error: stat module/./.terraform-docs.yml: no such file or directory
~/tf/ > terraform-docs --config $PWD/.terraform-docs.yml md module
Error: stat module/home/deepbrook/tf/module/.terraform-docs.yml: no such file or directory
```

The docs make no mention of this behaviour, and it strikes me as odd (being used to the described expected behaviour from pretty much all other CLI tools).

### Expected Behaviour
`terraform-docs` should use $PWD when resolving `--config` paths.

**Comment by kneufeld-pbp** [comment]
I just discovered this while trying to create a default configuration in my home directory.  It would be nice to set a default configuration at the user level and then have it be overridden if another config file is present or the flag is used.

**Comment by khos2ow** [comment]
#487 will fix this, and I managed to incorporate both of the suggestions there.
