### ISSUE TITLE
Change the behavior of `--sort` and `--sort-by` flags and config

### ISSUE THREAD

**Issue by khos2ow** [terraform-docs/terraform-docs#448]
### What problem are you facing?

Currently the `--sort` flag accepts a boolean to indicate "sort is enabled or not" and if so "sort by name", also there are two complementary flags for it: `--sort-by-required` and `--sort-by-type`. This doesn't scale well and can be slightly misleading and counterintuitive.

### How could terraform-docs help solve your problem?

Following changes are proposed:

- `--sort` remains unchanged
- deprecate `--sort-by-required`
- deprecate `--sort-by-type`
- add new flag `--sort-by` to accept an string for type of sorting with following acceptable values:
  - `name` (default)
  - `required`
  - `type`

**Comment by nitrocode** [comment]
The required are so important that I'd want them to be in their own subsection like this. But that might be a separate ticket.

## Inputs

All inputs

### Required

Required inputs

### Optional

Optional inputs

**Comment by khos2ow** [comment]
@nitrocode you are correct, your suggestion is a bit out of scope of this issue. But such a functionality does exist, albeit only for `markdown document`. You can check its [example](https://terraform-docs.io/reference/markdown-document/#example) in which if you run `terraform-docs markdown document --required /path/to/module` the output will be like follow:

```md
...

## Required Inputs

The following input variables are required:

...

## Optional Inputs

The following input variables are optional (have default values):

...
```

Alternatively for `markdown table` if you use the same `--required` flag, the _required_ ones are being shown on top of the table before the optional ones.
