### ISSUE TITLE
Document terraform plan symbols

### ISSUE THREAD

**Issue by sonic1981** [terraform-docs/terraform-docs#453]
### What problem are you facing?

As documented here (https://github.com/hashicorp/terraform/issues/14379), there doesn't seem to be anywhere where the `plan` symbols are displayed.

### How could terraform-docs help solve your problem?

Explain what each symbol means

**Comment by khos2ow** [comment]
Sorry for the delay. Purpose of `terraform-docs` is to generate documentation from modules, and it is not a documentation for Terraform itself (as a tool). That said, the best place to define and/or clarify the `plan` symbols, as you linked above, is exactly on https://github.com/hashicorp/terraform/ or maybe https://github.com/hashicorp/terraform-website.
