### ISSUE TITLE
Stop distributing standalone binaries on release

### ISSUE THREAD

**Issue by khos2ow** [terraform-docs/terraform-docs#454]
### What problem are you facing?

Following up on #377 and the announcement in [`v0.11.0`](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.11.0):

> Note: We've also enabled GoReleaser for the release workflow, and to be able to support all the use-cases we changed the distribution of assets from standalone binary to compressed files (tar.gz and zip). In the upcoming releases we're going to deprecate distribution of standalone binaries, please adjust any scripts accordingly.

### How could terraform-docs help solve your problem?

We're going to stop distributing standalone binaries on release process and only distributing compressed files (`tar.gz` and `zip`).

**Comment by nitrocode** [comment]
Oh that's interesting.

How come the standalone binaries will be removed ? I always found it convenient to download the appropriate binary for the system I was on instead of having to recompile it.

For homebrew, it doesn't seem like any [formula](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/terraform-docs.rb) updates would be necessary

**Comment by khos2ow** [comment]
This is not going to remove distribution of pre-compiled binaries for various systems altogether, rather we will be distributing a tarball (or zip on Windows) version of it which will contain README and LICENSE as well as pre-compiled binary.

One of the other reason is to be able to support [Scoop](https://github.com/terraform-docs/scoop-bucket). Otherwise the workflow has not changed so much and only adds one additional step to decompress the file.

[Pre-compiled Binary](https://terraform-docs.io/user-guide/installation/#pre-compiled-binary):

```bash
curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.11.2/terraform-docs-v0.11.2-$(uname)-amd64.tar.gz
tar -xzf terraform-docs.tar.gz
chmod +x terraform-docs
mv terraform-docs /some-dir-in-your-PATH/terraform-docs
```

**Comment by nitrocode** [comment]
Oh I see. Thanks for the added explanation.
