### ISSUE TITLE
Error when calling `markodwn document` with `--anchor false`. 

### ISSUE THREAD

**Issue by questsul** [terraform-docs/terraform-docs#457]
### Description

I was expecting for terraform-docs to create output without anchor links when called like:

```sh
terraform-docs markdown document . --anchor false
```

Instead It exits with error:
```sh
terraform-docs markdown document . --anchor false
Error: accepts 1 arg(s), received 2
```

### How can we reproduce it?

Tried this on several modules, works fine when used without `--anchor false` 

### Environment information

- terraform-docs version : 0.12.1 4714dd3 linux/amd64
- Go version: - 
- OS (e.g. Windows, MacOS): Ubuntu 20.04 WSL2 under Windows 10:

**Comment by questsul** [comment]
Thank you for quick response. For sure this is not a bug :)
I'm just wondering is it obvious? Or maybe the way that some flags are accepting arguments whitout `=` and others don't can be a bit confusing?

**Comment by khos2ow** [comment]
This is the natural behavior of Cobra (which we use internally), https://github.com/spf13/cobra/issues/613#issuecomment-357706597 shows different use-cases. I'm gonna add a note in documentation for it as well.
