### ISSUE TITLE
Add An Option for "tfvars hcl" command to Show Description on the variable

### ISSUE THREAD

**Issue by mikiya771** [terraform-docs/terraform-docs#461]
### What problem are you facing?

When:  Creating Terraform Template,
What:  I want to create tfvars from "variables.tf" with description for my template user.

I want to give my template users an experience that they can write tfvars only reading tfvars (not with variables.tf).

#### Example
input 
```
variables "some_var" {
  default = "test"
  description = "this is a test variable"
}
variables "some_var2" {
  default = "test"
}
```
output
```
/*
this is a test variable
*/
some_var = "test"

# no descriptions
some_var2 = "test"
```
full goal image: https://github.com/mikiya771/terraform-docs/blob/master/internal/format/testdata/tfvars/hcl-PrintDescription.golden

### How could terraform-docs help solve your problem?

I want to get the expected tfvars with an additional option like this.

```
terraform-docs tfvars hcl --description .
```

**Comment by khos2ow** [comment]
That's an interesting suggestion, although I think it can be done with couple of cosmetic changes:

1. use `#` comment instead of `/* */`
2. don't show anything if there's no description

```hcl
# this is a test variable
# with multiple lines
some_var = "test"

some_var2                = "test"
some_var3_with_long_name = "test"

# this is another test variable
some_var4 = "test"
```

**Comment by mikiya771** [comment]
@khos2ow Thank you for your quick response.
I agree with your two advices,
