### ISSUE TITLE
Extract custom functions for go templates into separate repository/module.

### ISSUE THREAD

**Issue by lokkersp** [terraform-docs/terraform-docs#485]
### What problem are you facing?
During the implementation of my own plugin for terraform-docs, I realized I couldn't use custom functions that are using in their own templates. I'm talking about [these functions](https://github.com/terraform-docs/terraform-docs/blob/master/internal/template/template.go#L45). Maybe they are located somewhere else too.

### How could terraform-docs help solve your problem?
Extract these functions to the standalone repository. I'm completely sure that custom plugins authors will be grateful for this change.

**Comment by khos2ow** [comment]
Now [`template/`](https://github.com/terraform-docs/terraform-docs/tree/master/template) package is publicly available and you can use it in your own projects. Let me know if this solves your us-ecase so we can close this issue.

Note that plugin will be refactored and there will be a breaking change in this release, keep an eye out for the release notes.
