### ISSUE TITLE
 Output Expansion {{ .Header }} {{ .Footer }} {{ .Body }}

### ISSUE THREAD

**Issue by jamroks** [terraform-docs/terraform-docs#486]
When using terraform-docs , I often face the situation where i want to customise a portion of the readme , without touching other part .

there is a : 
- header 
- footer 

where is the 
- body ? 

what i really would like to  see is this : 

For Injecting the HEADER: 
####     

For Injecting the BODY: 
####     

For Injecting the FOOTER : 
####     

I think this would be  more flexible for the user, in terms of injecting precisely the part of the document needed in exactly the area they wanted it to appear by using the expansion :
{{ .Header }} 
{{ .Body }} 
{{ .Footer }} 
 
 or even 
{{ .Inputs }} 
{{ .Outputs }} 
{{ .Modules }} 

I know there is this {{ .Content }} but i find the ".Content" not flexible enought for the user.  I don't have enough knowledge of the terraform-docs code to say if what i suggest is even possible or not .

**Comment by khos2ow** [comment]
This is a really good suggestion! What I'm thinking is to add a new item into config file, called `content` which knows about the following variables:

- `{{ .Header }}`
- `{{ .Footer }}`
- `{{ .Inputs }}`
- `{{ .Modules }}`
- `{{ .Outputs }}`
- `{{ .Providers }}`
- `{{ .Requirements }}`
- `{{ .Resources }}`

So eventually this is possible:

```yaml
# .terraform-docs.yml
...

content: |-
  Any arbitrary text can be placed anywhere in the content

  {{ .Header }}

  and even in between sections

  {{ .Providers }}

  and they don't even need to be in the default order

  {{ .Outputs }}

  {{ .Inputs }}
```

**Comment by jamroks** [comment]
Wow thanks a lot for taking this into account and releasing it . This is Awsome !!!
