### ISSUE TITLE
Make internal packages (format, print, ...) reachable from outside.

### ISSUE THREAD

**Issue by RonnanSouza** [terraform-docs/terraform-docs#494]
### What problem are you facing?
I'm trying to use terraform docs in an API to convert HCL to JSON, but since `format`, `print` and `cli` packages are internal modules, I can't use things directly. Instead, I have to Execute the cobra command passing args and redirecting the output, which is not the best approach.

### How could terraform-docs help solve your problem?
I think it's only renaming the module from `internal` to something else, or even creating an interface to be called from outside. WYT guys?

**Comment by khos2ow** [comment]
This was by design in terraform-docs, mostly to facilitate and streamline implementing and using [plugins](https://terraform-docs.io/developer-guide/plugins/). Have you explored that to build a plugin for your use-case?

That said #485 proposes to expose more template functions (which is still not triaged) which might help on this too.

**Comment by khos2ow** [comment]
@RonnanSouza I've opened #510 to move some of internal packages and make them public, in the meantime I'd appreciate it if you share your existing repo or sample code of how you're using (or intend to use) publicly exposed terraform-docs' packages.

**Comment by khos2ow** [comment]
@RonnanSouza I've finished up with #510, and you can start using terraform-docs as a library in your code. An example for your case can be like:

```go
import (
    "github.com/terraform-docs/terraform-docs/format"
    "github.com/terraform-docs/terraform-docs/print"
    "github.com/terraform-docs/terraform-docs/terraform"
)

func runTerraformDocs(modulePath string) (string, error) {
    config := print.DefaultConfig()
    config.ModuleRoot = modulePath // module root path (can be relative or absolute)

    module, err := terraform.LoadWithOptions(config)
    if err != nil {
        return "", err
    }

    formatter := format.NewJSON(config)

    if err := formatter.Generate(module); err != nil {
        return "", err
    }

    return formatter.Content(), nil
}
```

Note that, as it stands now, you are responsible to read and parse `.terraform-docs.yml` as part of your code. It can be straightforward to parse it against `print.Config`. Or alternatively, like example above, just directly instantiate it within the code and set any values needed.
