### ISSUE TITLE
Malformed version error in 0.13.0

### ISSUE THREAD

**Issue by jamiegDS** [terraform-docs/terraform-docs#495]
Hello maintainers!

### Describe the bug

Using latest version 0.13.0 (4354602), and taking a version constraint from the example configuration reference:

`version: ">= 0.13.0, < 1.0.0"`

yields: `Error: Malformed version: 0.13.0 4354602`

I would expect the version constraint be matched if using a correct version (as I am), or an informative error be given if the version I have installed does not meet constraints.

### How can we reproduce it?

To reproduce, add the version constraint to .terraform-docs.yml and try to generate any docs.

### Environment information

terraform-docs version 0.13.0 4354602 linux/amd64 BuildDate: 2021-04-30T20:31:56Z
Ubuntu 20.04
Installed via pre-built binary.

**Comment by jamiegDS** [comment]
My apologies, this was a `terraform` compatibility issue

**Comment by khos2ow** [comment]
This is actually valid and I was able to reproduce it. This is in fact a bug in terraform-docs!

**Comment by jsrice7391** [comment]
I just ran into this as well! I always wanted to put my limited go skills to the test.

**Comment by khos2ow** [comment]
@jsrice7391 feel free to get a crack at this, if you want! Most probably the problem is that somewhere here `version` mutates and results in `v0.13.0 4354602` instead of simply `v0.13.0`.

https://github.com/terraform-docs/terraform-docs/blob/90ccb84e5e96257c176a378159df79a087ecf0ae/internal/version/version.go#L52-L58

**Comment by jsrice7391** [comment]
@khos2ow It looks like the Homebrew formula is not reflecting the same version as what it gets in the full read.

https://github.com/terraform-docs/homebrew-tap/blob/8e63fa9955cda2c61cc58e7233ef28f10bf16b57/terraform-docs.rb#L8

Does it matter that the versions would not Return the same number between the version within go and the version within the formula?

**Comment by jsrice7391** [comment]
Got it, making a PR now!

**Comment by khos2ow** [comment]
> It looks like the Homebrew formula is not reflecting the same version

That's a good point, we need to unify the version behavior for `darwin`. But just to note this formula you linked is _one_ of the formulas available, the other (more official) one is at https://github.com/Homebrew/homebrew-core/blob/master/Formula/terraform-docs.rb.
