### ISSUE TITLE
Reference to file instead of include in How-To Docs

### ISSUE THREAD

**Issue by frugecn** [terraform-docs/terraform-docs#512]
In the "Include Examples" part of the How To's document, it references using file instead of include in the example:

  ## Example

  ```hcl
  {{ file "example-1/main.tf" }}
  ```

Should be:

  ## Example

  ```hcl
  {{ include "examples/example-1/main.tf" }}
  ```

**Comment by khos2ow** [comment]
Nice catch! Do you want to submit a PR?

**Comment by frugecn** [comment]
first time doing a PR in github, hopefully I figured it out correctly.

**Comment by khos2ow** [comment]
W00t! That's awesome :heart:
