### ISSUE TITLE
Formatting issues with markdown

### ISSUE THREAD

**Issue by JJibreel** [terraform-docs/terraform-docs#520]
### Describe the bug
In the markdown line breaks are being added and as a result breaking the Resource table.

### How can we reproduce it?
This is occurring specifically in the Resource section of the markdown and it occurs when several (5+) of the resources include hyperlinks.

### Environment information
- terraform-docs version: v0.14.1 and v0.13.0 (via gh-actions)
- Go version: 1.16.4
- OS: Windows, Ubuntu
![markdown](https://user-images.githubusercontent.com/62666365/121259732-75a34180-c87e-11eb-8672-b223244a8aff.PNG)
![markdown file](https://user-images.githubusercontent.com/62666365/121259755-79cf5f00-c87e-11eb-9080-43496ee90411.PNG)

**Comment by JJibreel** [comment]
Right, the ones without the hyperlink are broken / not in the table.

**Comment by khos2ow** [comment]
Can you provide the content of `required_providers` too? I'm interested to see the `source` attribute of `harness_application`.

**Comment by alexkrebiehlKR** [comment]
The broken resources are internal modules in the form of `git@github.com:team/repo.git`. The corresponding provider is also internal (e.g. `repo.company.com/providers/harness`)
