### ISSUE TITLE
Formatting issue indented code snippets

### ISSUE THREAD

**Issue by johankees** [terraform-docs/terraform-docs#521]
### Describe the bug

Code snippets that use "```" to format the code break the generated markdown when the code snippet has been indented, for instance when used in a list.

### How can we reproduce it?

The following code breaks the formatting of the markdown after the code snippet:

```md
1. Entry one with code

    ```json
    {
      "key": "value"
    }
    ```

1. This line is now broken
```

The generated code looks like this:
````md
1. Entry one with code

    ```json
    {
      "key": "value"
    }

```

1. This line is now broken
````

I.e. a line break has been added before the ``` and the spaces were removed.

### Environment information

<!--
- terraform-docs version (use `terraform-docs --version`):
- Go version (if you manually built. use `go version`):
- OS (e.g. Windows, MacOS):
-->
terraform-docs: v0.14.1
Go: go version go1.16.5 linux/amd64
OS: Linux/Ubuntu (Windows WSL)

**Comment by khos2ow** [comment]
I'm not sure if I understood it correctly. Where do you define this:

```
1. Entry one with code

    ```json
    {
      "key": "value"
    }
    ```

1. This line is now broken
```

**Comment by khos2ow** [comment]
> (without the \ in front of ```. I had to add that to make the formatting work)

Tip: using ` ``` ` (three backticks) is a convention, but it doesn't have to be exactly three, minimum is three actually. So for the latter code block you could've wrapped the whole thing inside ` ```` ` (four backtickes) then there was no need for escaping.

**Comment by johankees** [comment]
> I'm not sure if I understood it correctly. Where do you define this:
> 
> ```
> 1. Entry one with code
> 
>     ```json
>     {
>       "key": "value"
>     }
>     ```
> 
> 1. This line is now broken
> ```

We've got a "header markdown file" to describe how to use the module. The generated markdown is then appended. I.e. we use --header-from to add the snippet to the readme.

**Comment by johankees** [comment]
> > (without the \ in front of ```. I had to add that to make the formatting work)
> 
> Tip: using `` ``` `` (three backticks) is a convention, but it doesn't have to be exactly three, minimum is three actually. So for the latter code block you could've wrapped the whole thing inside `` ```` `` (four backtickes) then there was no need for escaping.

Thanks. Updated

**Comment by khos2ow** [comment]
> We've got a "header markdown file" to describe how to use the module. The generated markdown is then appended. I.e. we use --header-from to add the snippet to the readme.

Thank you for the explanation, I was able to replicate it.

**Comment by edgarsandi** [comment]
Hello guys!

@johankees 
I've been working on this issue for some days, and I found the cause [here](https://github.com/terraform-docs/terraform-docs/blob/master/internal/template/sanitizer.go#L299)

BTW, when I was coding the solution, which is not so trivial, I'm thinking about the initial problem.

Why do you need to keep these indentations before the codeblock triple backticks?

For example, if you just write this (without left spaces before the triple backticks):

~~~ 
1. Entry one with code

```json
    {
      "key": "value"
    }
```

1. This line is now broken
~~~

**Comment by johankees** [comment]
Hi @edgarsandi Good question. We need it because the indenting allows us to make the snippet part of the first bullet point. If we remove the indentation, the code is aligned to the left instead. This also breaks the numbering. So given your example, we would get something like this:

1. Entry one with code

```json
    {
      "key": "value"
    }
```

1. This line is now broken

(note the numbering is incorrect now)

But what we're looking for is:

1. Entry one with code

    ```json
        {
          "key": "value"
        }
    ```
  
1. This line is now broken

(it's correct now)

**Comment by khos2ow** [comment]
@edgarsandi are you still working on this?
