### ISSUE TITLE
terraform-docs changes provider markdown from a hard coded number to a tilde

### ISSUE THREAD

**Issue by nitrocode** [terraform-docs/terraform-docs#525]
See related issue: https://github.com/antonbabenko/pre-commit-terraform/issues/205

I'm unsure if this problem is due to our CI or if it's a setting with terraform-docs. We keep seeing our CI terraform-docs 0.14.1 change the provider markdown pins from a hard coded number like `3.45.0` to `~> 3.0` and our local terraform-docs 0.14.1 reverse the change.

How do we prevent this ?

**Comment by khos2ow** [comment]
This, in nature, is duplicate of #517. The reason you see different behavior is because, most probably, `.terraform.lock.hcl` is gitingored and your CI doesn't have it so it falls back on `~> 3.0` but your local workstations do have the file so the actual provider version is extracted.

**Comment by nitrocode** [comment]
Yes, that's the same issue. Thank you. I'll close this.
