### ISSUE TITLE
Providers are not sorted

### ISSUE THREAD

**Issue by RobCannon** [terraform-docs/terraform-docs#529]
### Describe the bug

The Providers section of the document is not sorted and it will generate in an unpredictable order each time documents are generated.  This is a problem for automatic document generation as every update produces a change in the document file

### How can we reproduce it?

Generate documentation for a terraform project that uses several providers.  Notice that the order of providers changes with each run.

### Environment information
terraform-docs --version
terraform-docs version v0.14.1 52f0ea0 linux/amd64
OS: Centos

**Comment by khos2ow** [comment]
I wasn't able to reproduce this, can you share a config that you have seen this issue with?

**Comment by RobCannon** [comment]
I am sorry, someone changed the sort flag to false in our configuration.  It's funny that providers are the only item that would randomly list in a different order, otherwise it would have been obvious what the issue was.  User error...

**Comment by azrdev** [comment]
See #622
