### ISSUE TITLE
Search for config in `.config` folder

### ISSUE THREAD

**Issue by politician** [terraform-docs/terraform-docs#531]
### What problem are you facing?

terraform-docs contributes to polluting the root path of a repository 🤮

Due to the proliferation of tools that store dotfiles in the root of a repo, it is getting very messy... Just look at this repo, most files at the root are tooling files creating noise around the important files.

Many people (including me) have started hiding those files in a `.config` folder whenever possible. Many tools already support it natively, it would be great if terraform-docs could support it also 🥳 

### How could terraform-docs help solve your problem?

Current config discovery:

1. root of module directory
2. current directory
3. `$HOME/.tfdocs.d/`

I propose:

1. root of module directory
2. _`.config/` of module directory_
3. current directory
4. _`.config/` of current directory_
5. `$HOME/.tfdocs.d/`

**Comment by khos2ow** [comment]
Thank you @politician for the suggestion!

**Comment by politician** [comment]
Thank you for implementing so quickly 🤘
