### ISSUE TITLE
Trivial change in the install documentation for MacOS

### ISSUE THREAD

**Issue by Damans227** [terraform-docs/terraform-docs#538]
I would like to add a small change in the terraform install documentation. Add the following example in the installation steps for MacOS:

or

```bash
brew install terraform-docs/tap/terraform-docs
```

This example is present in the **README.md** but not in the product documentation [available here](https://terraform-docs.io/user-guide/installation/). Lemme know if I can open a PR to modify [terraform-docs/docs/user-guide/installation.md](https://github.com/terraform-docs/terraform-docs/blob/master/docs/user-guide/installation.md). Thanks!

**Comment by khos2ow** [comment]
Nice catch, yes definitely go ahead! :+1:
