### ISSUE TITLE
Allow showing use of resources by filename

### ISSUE THREAD

**Issue by Marcus-James-Adams** [terraform-docs/terraform-docs#549]
### Show resource usage split by filename ( With option sub headers)

To make things easier for our team we have a basic main.tf (that included our header details) but then create a separate filename.TF for each key resource area within that layer, thereby keeping each file short and easy to debug.
Currently, we create a manual readme.md (that we append tfdocs onto the end of) that then lists each file, a copy of it's comments and what resources are then being used in it.  We find this really useful when bringing somebody new onboard or revisiting old code to easily remember what is where

eg
```
# main.tf
**Setups the core networking**
- resource.azurerm_resource_group.main
- module.network_spoke
- data.azurerm_client_config.current

# key-vault-shared.tf
**Creates the shared keyvault for the environment keyvault and sets access policies:**
Note: This uses the new way of creating keyvaults as a direct resource rather than a module

- resource.azurerm_key_vault.shared
- resource.azurerm_key_vault_access_policy.admin_access
- resource.azurerm_key_vault_access_policy.developer_access
- resource.azurerm_key_vault_access_policy.key_vault_access_policy_share_alertlogic

# security_rules_nsg_frontend.tf
**Sets up the security rules for the subnet**
- resource.azurerm_network_security_rule.ssh-access-database-subnet
- resource.azurerm_network_security_rule.rdp-access-database-subnet
- resource.azurerm_network_security_rule.octopus-access-frontend-subnet
- resource.azurerm_network_security_rule.http-access-frontend-subnet
- resource.azurerm_network_security_rule.https-access-frontend-subnet
- resource.azurerm_network_security_rule.app-gw-access-frontend-subnet

# security_rules_nsg_databse.tf
**Sets up the security rules for the subnet**
- resource.azurerm_network_security_rule.rdp-access-database-subnet
- resource.azurerm_network_security_rule.winrm-access-database-subnet
- resource.azurerm_network_security_rule.octopus-access-database-subn
```

### How could terraform-docs help solve your problem?

As tf docs is already scanning and getting the list of resources, data types etc it would save us a lot of time and manual effort if tfdocs could do this for us.

**Comment by khos2ow** [comment]
@Marcus-James-Adams sorry for the long delay to get back to this, I was preparing the required foundation for this.

As the use-case you described is not very common, in my opinion, and a bit complex terraform-docs will not be producing such an output out of the box, but, we've exposed all the building blocks for it so you can build it using go templating inside `content` configuration.

Take a look at the last example [here](https://terraform-docs.io/user-guide/configuration/content/#examples). That is more simplified than what you described, but it can give you an idea how to proceed with this. An example (without grouping by file name) can look a bit like:

```yaml
content: |-
  {{- $list := list -}}
  {{- range .Module.Resources -}}
    {{- $list = append $list .Position.Filename -}}
  {{- end -}}

  {{ range $k, $v := $list | uniq -}}
    # {{ $v -}}
    {{- printf "\n" }}

    {{- range $.Module.Resources }}
      {{- if eq .Position.Filename $v }}
        - {{ .GetMode }}.{{ .Spec }}
      {{- end }}
    {{- end -}}

    {{- printf "\n\n" -}}
  {{- end -}}
```

**Comment by nitrocode** [comment]
It would be nice too to separate only specific files and allow merging of others.

For example.

```
# for separating resources/inputs/outputs for all files
terraform-docs --separate-files="*"
```

```
# for specific files and then the rest of the files can have their resources/inputs/outputs/etc
# joined together as usual
terraform-docs --separate-files="context.tf"
```

**Comment by Marcus-James-Adams** [comment]
That worked perfectly for me thank you
