### ISSUE TITLE
terraform-docs fails if terraform files are blank

### ISSUE THREAD

**Issue by MaxymVlasov** [terraform-docs/terraform-docs#555]
### Describe the bug

>If you create a placeholder module with nothing in the terraform files and create a readme.md file pre-commit will fail with exit 1.
>i.e. main.tf, outputs.tf, and variables.tf
>
>We noticed this after creating a placeholder module we want to do work on but not necessarily in a particular PR.

Original creator: @cdobbyn
Moved from https://github.com/antonbabenko/pre-commit-terraform/issues/166

### How can we reproduce it?

```bash
mkdir bug
cd bug
touch README.md  main.tf  outputs.tf  variables.tf
terraform-docs markdown table .
```

### Environment information

- terraform-docs version: terraform-docs version v0.15.0 f3b6eab linux/amd64
- OS: Windows 10, WSL2 with Ubuntu 20.04.  
`Linux DESKTOP-C7315EF 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by khos2ow** [comment]
Nice catch! This should be easy to implement. It happens because we always attempt to extract header from `main.tf` (if that file exists) and we can easily skip extraction if the file content is empty.

**Comment by u5surf** [comment]
Hi, I have a quite simply dirty patch for this
```
diff --git a/internal/reader/lines.go b/internal/reader/lines.go
index c81502a..1ff83c9 100644
--- a/internal/reader/lines.go
+++ b/internal/reader/lines.go
@@ -54,6 +54,9 @@ func (l *Lines) extract(r io.Reader) ([]string, error) { //nolint:gocyclo
                }
                line, err := bf.ReadString('\n')
                if errors.Is(err, io.EOF) && line == "" {
+                       if l.FileName == "main.tf" && lnum == 0 {
+                               return lines, nil
+                       }
                        switch lnum {
                        case 0:
                                return nil, errors.New("no lines in file")

```

**Comment by khos2ow** [comment]
Thanks @u5surf, that looks good. Although I think it might be better to check it earlier than that in `Extract()`, maybe something like this:

```diff
diff --git a/internal/reader/lines.go b/internal/reader/lines.go
index c81502a..8ee5919 100644
--- a/internal/reader/lines.go
+++ b/internal/reader/lines.go
@@ -35,6 +35,13 @@ func (l *Lines) Extract() ([]string, error) {
        if err != nil {
                return nil, err
        }
+       stat, err := f.Stat()
+       if err != nil {
+               return nil, err
+       }
+       if stat.Size() == 0 {
+               return []string{}, nil
+       }
        defer func() {
                _ = f.Close()
        }()
```

and it can be easier to write a test for.
