### ISSUE TITLE
Whitespaces are being removed from parameter content

### ISSUE THREAD

**Issue by franviera92** [terraform-docs/terraform-docs#583]
I try perform follow

`content: |
  * parameters
    * name`

and get in readme

* parameters
* name

**Comment by franviera92** [comment]
> I did not understand your point, can you please elaborate the problem?

terraform-docs is not respecting the indentation when generating the README.md when I have a markdown list inside paremeto content that is inside .terraform-docs.yml

**Comment by khos2ow** [comment]
Oh I see your point, let me see how I can reproduce it.

**Comment by franviera92** [comment]
> Oh I see your point, let me see how I can reproduce it.

README.md
`- [CIF - CI/CD - IaC](#cif---cicd---iac)
  - [1. About](#1-about)
  - [2. Pre-requisites](#2-pre-requisites)
  - [3. Project structure](#3-project-structure)
    - [Dependencies](#dependencies)
  - [4. How to configure](#4-how-to-configure)
    - [Environment management](#environment-management)
      - [Example of GITLAB CI variable by environment with configuration minimum to deploy](#example-of-gitlab-ci-variable-by-environment-with-configuration-minimum-to-deploy)
    - [Flow CI:](#flow-ci)
    - [Requirements specific to Terraform](#requirements-specific-to-terraform)
    - [Providers](#providers)
    - [Variables](#variables)
      - [Terraform / Gitlab CI/CD Variables](#terraform--gitlab-cicd-variables)
    - [Outputs](#outputs)
      - [Terraform Variables](#terraform-variables)
  - [6. Operators](#6-operators)
  - [7. Related links](#7-related-links)
  - [8. Notes for contributors](#8-notes-for-contributors)
    - [README editing guidelines](#readme-editing-guidelines)`

.terraform-docs.yml
`content: |
    - [CIF - CI/CD - IaC](#cif---cicd---iac)
    - [1. About](#1-about)
    - [2. Pre-requisites](#2-pre-requisites)
    - [3. Project structure](#3-project-structure)
      - [Dependencies](#dependencies)
    - [4. How to configure](#4-how-to-configure)
      - [Environment management](#environment-management)
        - [Example of GITLAB CI variable by environment with configuration minimum to deploy](#example-of-gitlab-ci-variable-by-environment-with-configuration-minimum-to-deploy)
      - [Flow CI:](#flow-ci)
      - [Requirements specific to Terraform](#requirements-specific-to-terraform)
      - [Providers](#providers)
      - [Variables](#variables)
        - [Terraform / Gitlab CI/CD Variables](#terraform--gitlab-cicd-variables)
      - [Outputs](#outputs)
        - [Terraform Variables](#terraform-variables)
    - [6. Operators](#6-operators)
    - [7. Related links](#7-related-links)
    - [8. Notes for contributors](#8-notes-for-contributors)
      - [README editing guidelines](#readme-editing-guidelines)
`
