### ISSUE TITLE
Hide license header from generate doc

### ISSUE THREAD

**Issue by Shabirmean** [terraform-docs/terraform-docs#604]
### What problem are you facing?
- Whenever I generate the docs (in Markdown) for the Terraform module a license-header section is added to the top of the content. 
- This is something I don't want and would like to not generate at all or hide it.
- Since every run of the tool adds this license-header, github actions assumes that there was a change. I'd like nothing to be done if the only change is adding this license-header.

### How could terraform-docs help solve your problem?
- Is there an existing mechanism which i can use to prevent this header section from being created?
- If not is it feasible to have this supported?

**Comment by poojitha-bikki** [comment]
@Shabirmean have you already tried using relevant config to hide the header - https://terraform-docs.io/user-guide/configuration/sections/
```
sections:
  hide:
    - header
```

**Comment by Shabirmean** [comment]
@poojitha-bikki - I did not come across this document; thus I hadn't tried it. Let me try that and see if it works :). Thank you very much!
