### ISSUE TITLE
default bool variable is null but got empty string ""

### ISSUE THREAD

**Issue by PePoDev** [terraform-docs/terraform-docs#609]
### Describe the bug

I have use `terraform-docs tfvars hcl .` to generate template, for example

```hcl
variable "public_subnet_assign_ipv6_address_on_creation" {
  description = "Assign IPv6 address on public subnet, must be disabled to change IPv6 CIDRs. This is the IPv6 equivalent of map_public_ip_on_launch"
  type        = bool
  default     = null
}
```

What I got

```hcl
public_subnet_assign_ipv6_address_on_creation = ""
```

What I need

```hcl
public_subnet_assign_ipv6_address_on_creation = null
```

### Environment information

terraform-docs version v0.16.0 linux/amd64
wsl ubuntu 22.04

### Reproduce

clone this example repo `git clone https://github.com/terraform-aws-modules/terraform-aws-vpc && cd terraform-aws-vpc`

run `terraform-docs tfvars hcl . | grep public_subnet_assign_ipv6_address_on_creation`

output `public_subnet_assign_ipv6_address_on_creation = ""`

**Comment by sashasimkin** [comment]
I have the same issue, where terraform code relies on some variables being null.

I found that this functionality was added in https://github.com/terraform-docs/terraform-docs/pull/226

@khos2ow could you please explain the logic behind null -> "" transformation? was it intended or just it is what it is?

I tried digging into the code, but my go is not that good :(
