### ISSUE TITLE
OpenTofu support

### ISSUE THREAD

**Issue by skyzyx** [terraform-docs/terraform-docs#699]
### What problem are you facing?

https://opentf.org/announcement

We want to ensure that this project will support OpenTF in addition to Terraform.

From a technical perspective, I expect that it will be a no-op for the time being as OpenTF anticipates maintaining compat/interop for the foreseeable future. (However, OpenTF has stated that _some_ functionality may be added to OpenTF that is a _superset_ of what's in base Terraform. [[source](https://github.com/opentffoundation/roadmap/issues/24)])

From a process perspective:

1. If there is a bug in OpenTF that does not exist in Terraform (or vice-versa), will bug reports (as they pertain to this project) be treated equally on both platforms?

1. Will testing be performed with code targeting both platforms?

1. For OpenTF's potential future "superset" functionality, will that be treated as a first-class citizen?

**Comment by nitrocode** [comment]
I believe the domain in this url would be the only variable that would need to be overwritten using a flag/config

https://github.com/terraform-docs/terraform-docs/blob/577d2c88101b06207e6cf99845f259b9f2ed62c2/terraform/resource.go#L68

**Comment by nitrocode** [comment]
Can we rename the title to opentofu instead of opentf ?

**Comment by skyzyx** [comment]
Done.

**Comment by afischer-opentext-com** [comment]
Since OpenTofu 1.8.0 the file extension .tofu is supported (and some more https://github.com/opentofu/opentofu/pull/1738). 

That is e.g. useful for allowing new features or in my case: Allow RenovateBot/Renovate (https://github.com/renovatebot/renovate) to distinguish between Terraform and OpenTofu versions. Is there any plan to support additional file extensions next to .tf?

**Comment by ucfchandra** [comment]
Hello, I'd like to reopen the issue of support for .tofu files.

**Comment by skyzyx** [comment]
@afischer-opentext-com and @ucfchandra: I think that adding support for `.tofu` files should be a new, separate issue.

@nitrocode: I'm going to go ahead and resolve this issue as-is, and open separate issues for `.tofu` files and the registry URL.

**Comment by skyzyx** [comment]
https://github.com/terraform-docs/terraform-docs/issues/811
