### ISSUE TITLE
Discrepancies in the AWS Provider Version in README Documentation when utilizing terraform-docs  between ARM and AMD Architectures

### ISSUE THREAD

**Issue by katrinajaneczko** [terraform-docs/terraform-docs#704]
### Describe the bug

When running `terraform-docs .` on a system with an Apple M1 or M2 (ARM) chip, in the generated documentation, the provider version differs from systems with older chips (amd64). Specifically, the version for the AWS provider is not consistent.

This is causing an issue when collaborators with different architecture are working on the same Terraform project. Say user 1 has ARM architecture and user 2 has AMD architecture. Then if user 1 pushes a change after running `terraform-docs .` and user 2 pulls the change and runs `terraform-docs . --output-check`, an error is thrown: `Error: README.md is out of date`. Vice versa if user 2 pushes and user 1 pulls and checks.

### How can we reproduce it?

1. On a system with an Apple M1 or M2 (ARM) chip, run `terraform-docs .` 
<img width="216" alt="Screenshot 2023-09-11 at 1 59 17 PM" src="https://github.com/terraform-docs/terraform-docs/assets/73796086/ddf96de2-844b-4e82-86b4-f0d2225ae434">

2. On a system with an older chip (amd64), run `terraform-docs .`
<img width="204" alt="Screenshot 2023-09-11 at 1 56 18 PM" src="https://github.com/terraform-docs/terraform-docs/assets/73796086/adc7cc08-bff4-443e-a891-a6390ae6a55f">

3. Compare the generated documentation for the AWS provider version.

### Environment information

- On MacOS ARM Architecture: 
     - Chip: `Apple M2 Pro`
     - `terraform-docs version v0.16.0 darwin/arm64`
     - `go version go1.21.0 darwin/arm64`
- On MacOS AMD Architecture:
     - Chip: `Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz`
     - `terraform-docs version v0.16.0 darwin/amd64`
     - `go version go1.21.0 darwin/amd64`

### Additional Information

This is causing an issue when collaborators from our team with different architecture are working on the same Terraform project. There is a task in our CI/CD pipeline that runs `terraform-docs . --output-check` from a Docker container with the amd64 architecture. When changes were pushed from a Mac with an M1 or M2 chip, the inconsistency in the generated documentation versions causes the pipeline to fail with `Error: README.md is out of date`. However, on my local machine (M2 chip), it reports that the documentation is up to date.

This is the workaround I am using:
<img width="839" alt="Screenshot 2023-09-11 at 10 14 53 AM" src="https://github.com/terraform-docs/terraform-docs/assets/73796086/3bd64580-b4cb-4fc8-b960-f3535f8334aa">

These AWS provider version on line 61 pictured above must match that on line 55. So for this module, if I have the M1 or M2 chip, I must make a manual correction before I make a commit. In the README I need to replace `5.13.1` on line 61 with `>= 5.0.0`. Since we have a pre-commit hook which also runs `terraform-docs . --output-check`, I also need to use the `--no-verify` flag when commiting in order to ignore pre-commit hooks, which otherwise would raise an error and not let me commit, since according to my version of terraform-docs the README is not up to date.

**Comment by grimm26** [comment]
are you sure it is not a case of `terraform init` having run at a different time from the different users?

**Comment by bgshacklett** [comment]
I thought I was in the same boat, but it was an issue with `.terraform.lock.hcl` existing on my machine, but not being checked into Git.

**Comment by pawelpesz** [comment]
I believe explicitly setting the `lockfile` option to `false` should make this unwanted discrepancy go away 😄 

https://terraform-docs.io/user-guide/configuration/settings/#lockfile

**Comment by pascal-hofmann** [comment]
This happens when `.terraform.lock.hcl` is not in sync. Please create it for all required platforms at once and check it into your git repository.

I use this to generate it for all common platforms:
```
rm -f .terraform.lock.hcl
tofu providers lock -platform=linux_arm64 -platform=linux_amd64 -platform=darwin_amd64 -platform=darwin_arm64 -platform=windows_amd64
```
