### ISSUE TITLE
Please release v0.18.0

### ISSUE THREAD

**Issue by cyclops23** [terraform-docs/terraform-docs#771]
I'm looking to take advantage of  https://github.com/terraform-docs/terraform-docs/pull/770 in my Github Actions workflow but I believe that would need a new release of both `terraform-docs/terraform-docs` and `terraform-docs/gh-actions`.  

Please could these be released (or if releases happen at a set cadence could someone let us know when the next releases will be)? 🙏

**Comment by hom3r** [comment]
@cyclops23 I see that [version 0.18.0 was released today](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.18.0) 🚀 I believe this ticket can be closed ✅

**Comment by cyclops23** [comment]
`terraform-docs/gh-actions` also needs a new release but I can open a separate issue in that repo.
