### ISSUE TITLE
Copy button blocking code text

### ISSUE THREAD

**Issue by dan-cbm** [terraform-docs/terraform-docs#807]
### Describe the bug
On [this page for example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_public_access_block), you cannot read some of the code blocks due to the copy button permanently blocking some of the code. Resizing the page doesn't help (much)
![image](https://github.com/user-attachments/assets/f6ff2452-825e-45db-a41e-f31d894498a4)

### How can we reproduce it?

visit the link above and take a look

### Environment information

Ubuntu, firefox visiting offical docs page

**Comment by pascal-hofmann** [comment]
Hi,
this repository is for terraform-docs, an open source tool to generate documentation based on terraform code. It is not affiliated with Hashicorp and does not power the documentation on registry.terraform.io.
